### ISSUE TITLE
Why not use GitHub release notes?

### ISSUE THREAD

**Issue by olivierlacan** [olivierlacan/keep-a-changelog#1]
@searls offers this example: https://github.com/linemanjs/lineman/releases

My retort: 

> @searls Sure, but that’s not portable. It’s already hard to convince OSS maintainers to keep a changelog, this is even harder.
## Portability

I think the portability problem is a huge showstopper. Something that can't live with the repo will disappear if the project moves from GitHub, or just simply isn't accessible offline with the codebase in hand.

I think that's a problem for GitHub to address if they want to see people adopt their release notes platform. 
## Tags

This however is a neat idea although I find tags much more obscure than some people seem to realize. The git interface is pretty poor I think, and the visibility from various clients, although better than before, is still not great. That's the one part of GitHub's implementation of Releases notes that I do like, however, since they are portable.

I don't know if it's possible using git, but it would be nice if the GitHub release description was stored in the tag description itself.

![image](https://cloud.githubusercontent.com/assets/65950/3374299/98c2d57c-fbbc-11e3-97d1-ed119dd92fa7.png)

**Comment by olivierlacan** [comment]
@technoweenie Using `git tag -a v0.0.8 --cleanup=whitespace` I managed to create a tag message with Markdown (I just made sure to put a release title on the first line).

![image](https://cloud.githubusercontent.com/assets/65950/6227855/16336172-b6a5-11e4-8443-15535bd7cf33.png)

Now it is sort of weird that release (despite being linked to the tag) doesn't take any hints from the tag message: 

![image](https://cloud.githubusercontent.com/assets/65950/6227873/4655764c-b6a5-11e4-8578-039f8da783f1.png)

**Comment by elyscape** [comment]
I sent a suggestion in to GitHub about that a week or two ago, actually.  Hopefully they implement it sometime.

**Comment by mattbrictson** [comment]
I just created a tool called "chandler" to sync a project's `CHANGELOG.md` to GitHub's Releases to solve this problem. It can be manually invoked on the command line, or you can also add it to the Rakefile of a existing Ruby project such that `rake release` syncs the CHANGELOG to GitHub Releases automatically as part of the rubygems release process. It works by using the GitHub API via octokit.rb.

It is still early days, and I'd like to make it useful for a wider audience. Critique and suggestions are welcome! 

https://github.com/mattbrictson/chandler

**Comment by Abdillah** [comment]
Great tools, @mattbrictson! A wider audience maybe planning for integrating with git (`git-chandler`) and support more git hosting.

**Comment by olivierlacan** [comment]
Covered in http://keepachangelog.com/en/1.0.0/#github-releases

**Comment by Mouvedia** [comment]
> If I attempt to edit the Release to fix this, the pre-existing annotation disappears completely

@olivierlacan does it still happen? Is there a way to avoid the first line auto population?
