### ISSUE TITLE
fr-FR

### ISSUE THREAD

**Issue by dehboris** [olivierlacan/keep-a-changelog#101]
I want to create the french version.
How can do?

**Comment by NumEricR** [comment]
You have to create a "index.haml" file (with your translations) in a new dedicated folder & a new link in layout.haml.
Check what have been done for [the german translation PR](https://github.com/olivierlacan/keep-a-changelog/pull/90/commits/fc51f1fbc27ede85354a501cb104f1114355e283).

**Comment by dehboris** [comment]
@NumEricR Ok thanks you

**Comment by olivierlacan** [comment]
@dehboris Please open a PR whenever you're ready. Thanks.
