### ISSUE TITLE
Start versioning Keep a Changelog 

### ISSUE THREAD

**Issue by olivierlacan** [olivierlacan/keep-a-changelog#103]
This will allow us to know which version has been translated and not mix up all the changes between languages.

**Comment by ypid** [comment]
It could also be used to refer to a specific version of Keep a Changelog. I for example like to explicitly refer to the latest stable version of Semantic Versioning with: http://semver.org/spec/v2.0.0.html (as the time of writing).

**Comment by olivierlacan** [comment]
Absolutely. I'm struggling with Jekyll's very awkward redirection options in #110. If you can provide help, that'd be great.

**Comment by olivierlacan** [comment]
Done! http://keepachangelog.com/
