### ISSUE TITLE
it-IT

### ISSUE THREAD

**Issue by roalz** [olivierlacan/keep-a-changelog#106]
Gentlemen,
I would like to contribute to keep-a-changelog with the Italian translation.
I see I must create a /source/<language>/  directory and put the translated index.haml there, but I have a few questions:

1. language code: should it be just generic "it" or better to use the regional "it-IT"?

2. I'm new to HAML, nearly never used Ruby, etc:
it looks like any UTF-8 text editor can be used to edit HAML, is this correct?

3. How can I test/probe that the HAML will be correctly converted to HTML? (I'm trying using 'gem install haml' then 'haml index.haml' on Ubuntu Linux, but I'm missing redcarpet-whatever dependency...).

In general, it's not clear to me how a contributor can check his own changes before a maintainer can trigger a "publish".
It would be great to expand on CONTRIBUTING.md with the answers to the above questions, too.

Thank you

**Comment by roalz** [comment]
In the meanwhile, I've send a PR with the Italian translation (I used it-IT and just the web editor provided by Github, it was easier).

HTH

**Comment by olivierlacan** [comment]
Closing since the PR is open and waiting for feedback. #107
