### ISSUE TITLE
Changelogs aren't only used in open source

### ISSUE THREAD

**Issue by stevenbeeckman** [olivierlacan/keep-a-changelog#109]
I think changelogs are useful not only in open source software but also in closed source software. Can we remove any references to open source so these guidelines can be ported to closed source software writing teams as well?

**Comment by svetlyak40wt** [comment]
Steven, I belive, you can make youself a closed source fork of this repository and make these changes there ;-)

**Comment by kusma** [comment]
This was already addressed in commit 5daa2fda5733538b70abe394798e8612e38c5de3...
