### ISSUE TITLE
Subtypes of changes

### ISSUE THREAD

**Issue by ScottFreeCode** [olivierlacan/keep-a-changelog#111]
I'm a fan of the idea that the change log is your user/consumer-facing<a id="footnoteReference" href="#footnote">*</a> description of changes whereas your git commit log is you developer/maintainer-facing description. However, even among user-facing changes there are some important distinctions besides whether stuff was added, removed, fixed etc.; specifically, there's a decent correspondence of the added/removed/etc categories to backwards-compatible and backwards-incompatible interface changes _if what is being changed is functionality_, but it might be important to tell users that documentation, examples or metadata have changed as well (documentation and examples are written largely for them in the first place, and metadata -- such as package info -- straddles the fence between documentation and functionality: it can shape either depending on how it's used). I would like to suggest that these subtypes be listed as well as Added, Removed etc., either in combination ("Added Documentation", "Removed [Functionality]" [if omitted, functionality is implied?]) or as another level.

The syntax I've been trying for this so far is to add it at the start of the "- " entries in the format "`[subtype]`", with omitted subtype implying functionality. This is similar to how many projects tag change-log entries with additional info, subtypes or associations already, only I think my tags for documentation etc. changes are more in the spirit of user-centricity than most. I'd be open to trying a hierarchical scheme instead, with the below caveats.

Given that I also prefer to order my change log entries with security on top, backwards-incompatible non-security changes next (without doing anything to highlight that they're "breaking", leaving it implicit in the Removed, Changed and Deprecated types for functionality) and backwards-compatible non-security changes last, I guess I would apply ordering by whether changes affect functionality first (no subtype, metadata depending on the content of the metadata) and then by whether it's security, backwards-incompatible or backwards-compatible.

Alternatively, the ordering issue becomes cleaner if the Added, Removed etc. hierarchy is either itself below the Functionality, Metadata, Documentation & Examples hierarchy level, or else combined with it like "Changed Metadata", "Fixed Examples" etc., but then the Added, Removed etc. groups are split up (although it would avoid confusion with the ordering rationale).

Anyone have any thoughts?

<a id="footnote" href="#footnoteReference">*</a> That is, users in both the end user sense and in the sense of other developers making use of your library/program in their own, as distinct from developing/maintaining your library/program itself; I'll refer to them all as just "users" for the rest of this.

**Comment by olivierlacan** [comment]
I think you're overthinking this a tad. A change is a change is a change. I don't think it's that valuable to differentiate documentation changes to functionality changes. We very purposefully say "notable" changes. Anything you deem notable or your users would deem notable is something you should cover. Significant new documentation is notable, as is new or altered functionality. 

The ordering issue seems disconnected from your main point. I think the order is not very significant other than with large releases where you'd obviously want to prioritize certain sections if you want to make the release about changes, or new features, or deprecations. I don't think we need to have rigid guidelines in that regard.

**Comment by ScottFreeCode** [comment]
More likely overexplaining; I remember having some particular motivation for considering the matter at all (I mean, besides my taste for being very organized), but apparently I failed to capture it with simplicity/clarity because I can't remember it now re-reading my post... My main reaction now is, "Wait, do I even need to put documentation-only changes in the changelog? The changelog itself is part of the documentation." Oh well.

**Comment by olivierlacan** [comment]
@ScottFreeCode If it comes back to you, don't hesitate to... document it here ;-)
