### ISSUE TITLE
Icon Request: CHANGELOG

### ISSUE THREAD

**Issue by ajsb85** [olivierlacan/keep-a-changelog#117]
![image](https://cloud.githubusercontent.com/assets/663460/17331684/48ed9054-58cc-11e6-8e3d-b98cbd70bee1.png)

![image](https://cloud.githubusercontent.com/assets/663460/17331688/4c9038f6-58cc-11e6-96f1-c8e8fd5d19a4.png)

https://github.com/robertohuertasm/vscode-icons/issues/125
https://github.com/FortAwesome/Font-Awesome/issues/9689

**Comment by olivierlacan** [comment]
Hey there. Interesting idea but a changelog is very different from your typical `.log` file which usually contains automated logging information. If we created an icon we'd probably need to find a way to emphasize the ideas of time, curation, and periodicity (releases).

**Comment by ajsb85** [comment]
![image](https://cloud.githubusercontent.com/assets/663460/17334856/1682dbae-58d8-11e6-8bbb-54f99d1857f0.png)
![image](https://cloud.githubusercontent.com/assets/663460/17334858/19451adc-58d8-11e6-841f-27cf74b54318.png)

**Comment by ajsb85** [comment]
Thank you
