### ISSUE TITLE
Why are versions not prefixed by `v`?

### ISSUE THREAD

**Issue by liviu-** [olivierlacan/keep-a-changelog#120]
This may have been clarified before, but I couldn't find an answer to this -- Why are the versions in the change log simply `X.Y.Z` instead of `vX.Y.Z`?

**Comment by olivierlacan** [comment]
What does the `v` stand for? :-)

**Comment by olivierlacan** [comment]
I'll answer the rhetorical question. `vX.Y.X` is a naming convention for git tags. It allows to differentiate things are not version tags from version tags. So `problem` from `v1.2.3`, since git tags are not used exclusively for tagging versions. 

There's no point in showing `v1.2.3` on a change log since by nature every version number corresponds to a version (`v`).

Hope that helps.

**Comment by liviu-** [comment]
These are all good points indeed. To support the other position however:

- Due to the naming convention used for tags, releases also tend to be named with a `v` prefix ([commit message example](https://github.com/olivierlacan/keep-a-changelog/commit/ac3de665fcd6ef02786bc776c52dae55297f2a8d)) -- is naming consistency among releases, tags, change logs, and potentially documentation an issue to consider?
- Although contextually it may be obvious that the numbers in the change log refer to versions, would a prefix not contribute towards emphasizing the version meaning of an otherwise loosely formalised period-separated number? (explicit vs. implicit)

I appreciate that this is all subjective, but I'm curious about the reasoning.

**Comment by olivierlacan** [comment]
I don't think dot separated version numbers are loosely formalized. They're used in every software ever. `v`-prefixed versions are exclusively used by developers in projects that require the need to differentiate such versions from other colliding concepts: like git tags.

We're writing changelogs for humans. Humans don't need to distinguish between a random git tag and a version number. If they're reading a changelog, they know that `1.2.3` and `1.2.4` are two different versions of the software for which they're reading a changelog. 

There's no ambiguity there. `v` is a conventional implementation detail that doesn't need to be presented to the end-users of a changelog.

**Comment by liviu-** [comment]
> `v`-prefixed versions are exclusively used by developers

I see your point, though the `v` is not always hidden (e.g. GPLv1/GPLv2).

In any case, thanks for taking the time to clarify the reasoning behind the idea, and for fleshing out a well thought out project :+1:
