### ISSUE TITLE
"Dates in region-specific formats" section incredibly US-centric (and wrong)

### ISSUE THREAD

**Issue by amueller** [olivierlacan/keep-a-changelog#121]
This section currently says

> while many people in the rest of the world write a robotic-looking "2 June 2012", yet pronounce it differently. 

This might be robotic looking to someone from the US. In Germany, you'd write 2. Juni 2012, and it would be not considered robotic at all. Also, it would be pronounced exactly as it is written.

**Comment by Blaisorblade** [comment]
Agreed—also, you don't need to argue that point to convince people to pick ISO standard dates.

**Comment by olivierlacan** [comment]
Most changelogs are written in English, the most common human-friendly English date format is "June 2nd, 2016". 

I'm not from the U.S. I'm French. I say "2 Juin 2012" but in English "Two June 2012" sounds absurd unless you do the British mental gymnastic of switching the order in your head to "June Two" or "June 2nd". 

This is similar to Americans writting "$15" and saying "fifteen dollars". 

ISO dates are nice, consistent, sortable, but you definitely can't argue that they are easier to parse and read in English.

So to respond to your claim that this section is U.S.-centric. It's not, it's simply attempting to pave the cowpath. If you don't like the ordinal U.S.-style date format, then go ahead and use ISO. But remember that you're not making the changelog for you, but for the majority of your end-users.

**Comment by amueller** [comment]
Sorry, I don't understand your argument on multiple levels.

>  But remember that you're not making the changelog for you, but for the majority of your end-users.

That's my point exactly. Most end-users will not be from the US or native speakers of US English.

And I'm not sure how reading out loud factors into this. I really don't think many people read changelogs out loud. Or are you saying that it's harder for readers that rely on subvocalization? That seems pretty fabricated.

**Comment by Blaisorblade** [comment]
The website does recommend ISO dates, unlike suggested by @olivierlacan's comment. So all is well on that point. Does that help? Gonna answer the rest in a moment.

**Comment by Blaisorblade** [comment]
> Most changelogs are written in English, the most common human-friendly English date format is "June 2nd, 2016".

> I'm not from the U.S. I'm French. I say "2 Juin 2012" but in English "Two June 2012" sounds absurd unless you do the British mental gymnastic of switching the order in your head to "June Two" or "June 2nd".

First, the website advocates against "06-02-2012", which is both robotic-looking and ambiguous. I guess we agree on this recommendation—making things unambiguous is the most crucial point.

Second, the website and its changelog use ISO dates.

Third, in your comment you seem to advocate writing "June 2nd, 2016", unlike on the website. That's not ambiguous, but it seems it's only natural in the US.
By all sources I can find (beyond what I've been taught), in British English you usually write "2 June" and pronounce it "the 2nd of June", no swap needed. "June the 2nd" is mostly American, though Wikipedia claims it used to be also used in Britain and it remains used in British newspapers.

http://dictionary.cambridge.org/grammar/british-grammar/writing/dates
https://en.wikipedia.org/w/index.php?title=Date_and_time_notation_in_the_United_Kingdom&oldid=762706421#English
http://www.englishlessonsbrighton.co.uk/how-to-write-dates-british-american-english/
