### ISSUE TITLE
SemVer Sections

### ISSUE THREAD

**Issue by majgis** [olivierlacan/keep-a-changelog#124]
I find that I immediately want to map group names to major, minor or patch.  What do you think about  arranging each change group under a SemVer version?

I see these benefits:
- Clear communication of SemVer rules in relation to these change log guidelines
- Any discussion on the classification of a change has already taken place in pull requests with changes to CHANGELOG.md
- When it is time to release the new version number is immediately evident

Here is how I visualize the hierarchy:
- Major
  - Changed
  - Removed
  - Security
- Minor
  - Added
  - Deprecated
  - Security
- Patch
  - Fixed
  - Security

**Comment by majgis** [comment]
Here's an example of what I was thinking.
```
## [2.0.0]
### Major
####Changed
- broke api hard
### Minor
#### Added
- super cool new feature
#### Security
- use ---super-safe option to ward off evil spirits
### Patch
#### FIxed
- an old dependency was updated

## [1.8.0]
###Minor
####Added
- super cool new feature

## [1.7.5]
###Patch
####Security
- old dep with security issue updated
```
It probably just complicates things.
I'll just make a mental note that the existing headings in no way correlate to semver

**Comment by majgis** [comment]
Here is an example of a change log using semver headings: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#4.5.0

**Comment by majgis** [comment]
I've been using the format outlined above since I created this issue, and I've come to really like it.  Would you take a PR or fork?

**Comment by majgis** [comment]
I decided to do my own thing, with and emphasis on a cli tool: https://github.com/majgis/change-log
Thank you for the inspiration!

**Comment by matteoolivi** [comment]
AFAIU this projects aims to be unopinionated about how versioning is done - doing what you suggest would scratch that and couple it with semver.
