### ISSUE TITLE
fr-FR translation

### ISSUE THREAD

**Issue by rbecheras** [olivierlacan/keep-a-changelog#127]
I will do the translation to French.

**Comment by rbecheras** [comment]
Just created the `translation_fr-FR` branch for that purpose

**Comment by olivierlacan** [comment]
@rbecheras Can you review the released French translation and compare it to your version: https://github.com/olivierlacan/keep-a-changelog/blob/master/source/fr/0.3.0/index.html.haml

I'm sorry I missed your issue. Generally feel free to submit Pull Requests if you have translation suggestions or edits.

**Comment by olivierlacan** [comment]
I'm going to close this issue, but if you're interested in reviewing the newest version, check it out: http://keepachangelog.com/fr/1.0.0/
