### ISSUE TITLE
Where to list code names

### ISSUE THREAD

**Issue by beatngu13** [olivierlacan/keep-a-changelog#140]
Many projects use (marketing) code names for their releases, just think of [Ubuntu](https://wiki.ubuntu.com/DevelopmentCodeNames) or [OS X](http://www.imore.com/macos-version-code-names).

Does Keep a CHANGELOG make any recommendations where to list such names? If not, would it make sense to do so? I thought about something like:

## [0.3.0] Baz - 2015-12-03
...

## [0.2.0] Bar - 2015-11-04
...

## [0.1.0] Foo - 2015-10-06
...

**Comment by marc0tjevp** [comment]
I have been doing this for a long time now. I think it's really clean and clear.

**Comment by olivierlacan** [comment]
We don't but this makes sense.

**Comment by beatngu13** [comment]
So I'd say we use this issue to debate different styles. Depending on what we want to draw attention to (version number or code name), this may vary.

Personally, I think code names are somewhat optional and they probably only appear in major releases. Hence, the change log should focus on the version number. For instance:

## 2.0.0 (Baz) - 2015-12-03
...

## 1.1.0 - 2015-10-06
...

## 1.0.0 (Foo) - 2015-10-06
...

**Comment by ryanturner** [comment]
I agree, the version number is more immediately beneficial than a name, especially when organizations do not offer a code name for every release.

**Comment by olivierlacan** [comment]
Right after the version number definitely make sense since it's where people usually display release codenames.

**Comment by gilmrjc** [comment]
There is no entry for this in the FAQ, could you reopen this issue?
