### ISSUE TITLE
What about beta and RC releases?

### ISSUE THREAD

**Issue by avvertix** [olivierlacan/keep-a-changelog#146]
I'm wondering how to threat release candidates and beta releases. Currently I'm thinking to keep the changes in the _Unrealeased_ section, but this somehow go in contrast with the fact that I still have a version tag in my git repository. Any suggestions?

**Comment by Art4** [comment]
I don't see a problem to threat them the same like every other semver version?

```
## [1.0.0] - 2017-03-01
### Added
- finally stable

## [1.0.0-RC1] - 2017-02-15
### Changed
- more fixes

## [1.0.0-beta1] - 2017-02-01
### Changed
- some fixes

## [0.3.0] - 2017-01-01
### Added
- a feature
```

**Comment by avvertix** [comment]
I see. I was only thinking to keep the changelog file closer to the developers/users of the stable version of the project, as I tend to consider beta and RC versions with a shorter lifespan than the release to the public.

Probably it depends on the scope of the project, if is a library you might want to document everything, while in other projects might not be necessary.

**Comment by Art4** [comment]
In scope of a library imho you are right. I don't think it is important to define the importance of a version. Just document the changes and a developer will look for the changes affecting him.

In other projects I'm not sure if the users care about every change. And I think, they don't even care about a version number and every small fix.

In my projects I handle it like this:
- I document every change in the changelog. The target group for this are mostly developers.
- For other users I create a "What's new?" document, (in most cases) remove the version number, sum up the changes and reference the changelog for more details.

**Comment by avvertix** [comment]
Thanks for the great chat, I think I will apply your principles also to my projects

**Comment by Art4** [comment]
You're welcome. Glad if I could help. 🙂
