### ISSUE TITLE
Discuss why the changes matter

### ISSUE THREAD

**Issue by petdance** [olivierlacan/keep-a-changelog#147]
> To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.

I think it would be helpful to explain why exactly those changes are so important.  Explain the scenarios of, for example, user wanting to know if she should upgrade from version 1.83 to 2.10 of your project.  If she does, what changes will she have to make?

Or alternately, if she has a newer version but has to move back to a previous version because of breakage, how far back should she go?

**Comment by olivierlacan** [comment]
Check out http://keepachangelog.com/. Version 1.0.0 is a lot more refined than 0.3.0 was.

The breakage/rollback situation is very project specific. That's not something I think we should get into for this project.
