### ISSUE TITLE
Where to keep the changes

### ISSUE THREAD

**Issue by DannyvanHolten** [olivierlacan/keep-a-changelog#149]
I like to work with git flow. So i create features in different branches. Then merge them to develop, and finally tag them to master.

The question we have here, where do I keep my changes in my Changelog.

There are 2 alternatives:
- Write all the changelog items in the unreleased heading to the master branch. Change the changelog before creating a new tag and move all unreleased items to their version.

- Write all the changelog in the unrelease heading to their features. Merge them to the develop & resolve merge possible conflicts.  Change the changelog before creating a new tag and move all unreleased items to their version.

This repo doesn't give me a guideline about this, and we're internally having a discussion about it. What is your view on this?

**Comment by roalz** [comment]
Just my 2 cents.
I'm not 100% sure that keep-a-changelog should contain guidelines on how to manage changelogs from git-flow like feature branches.

Anyway, I would go with the second alternative: 
1. changelog for a feature goes to the unreleased heading of the changelog file in the corresponding feature branch (logic: who is working on the branch knows what to include in the changelog, and just work IN the context of that branch, no need to switch to master just for editing the changelog),
2. when a feature is git-flow closed, the merge in develop will bring the feature related unrelease changelog items in develop as well (potentially they can also be further edited?)

Then (but this is not strictly related to feature branches or git-flow), when releasing a version,
from develop a "release vX.Y" branch is created, and in there the changelog should be edited to move unreleased heading to version X.Y (most probably just before releasing the version and merging to master and tagging the release.

**Comment by beatngu13** [comment]
We're using Git Flow in combination with Keep a CHANGELOG as follows (which is similar to your second alternative):

- `feature` branches update the `"Unreleased"` section themselves. This has several advantages:
  - As mentioned by @roalz, whoever works on that branch probably knows best what to put into the changelog.
  - When there's a regression and a merge commit gets reverted, the changelog is automatically updated, i.e. features that are no longer part of the `develop` branch disappear.
- When a `release` branch is started, things stay in the `"Unreleased"` section until testing is done.
  - Maybe there will be additional fixes that have to update the changelog, too.
  - As soon as the  release tag is created, `"Unreleased"` is changed to the corresponding version number and a new `"Unreleased"` header is added at the top.
  - When the `release` branch is merged into `develop`, possible merge conflicts get resolved and the changelog is updated as well.

**Comment by DannyvanHolten** [comment]
Thanx! :)
