### ISSUE TITLE
Keeping it DRY by writing it at the point in a structured format

### ISSUE THREAD

**Issue by coedycode** [olivierlacan/keep-a-changelog#15]
## Starting with a TODO comment block

Quite often I'll write a todo comment not just as a bookmark for what's to do later, but for the work I'm about to do right then.  This is the point at which I'm most aware of what I'm adding, removing, deprecating or fixing,  so a structured comment block might be quite easy to add near the code I'm working on. 

The structure of this could use tags, i.e. 'CHANGELOG; NEWS; Commit Message' so that when the work is committed, a pre-commit process extracts the specially formatted comment blocks and appends the categorised and itemised content to the places it's been tagged for.

Strikes me that this could help focus the mind on the work that's about to be done, avoid forgetting important bits when it comes to the commit messages and keep the commit message useful, and produce a standardized changelog.

The downsides being the parsers that'd be needed to extract the comment blocks from all the languages worked with, and the discipline of writing structured comment blocks at the point.

Anyway, just another idea to put in the pot.

P.S. was inspired to write after starting to listen to the changelog podcast episode.

**Comment by lunemec** [comment]
Maybe this would be good use-case suggestion for The tool https://github.com/olivierlacan/keep-a-changelog/issues/51
