### ISSUE TITLE
Help to translate translation out-of-date notice in all languages

### ISSUE THREAD

**Issue by olivierlacan** [olivierlacan/keep-a-changelog#151]
This is a plea for help from @tianshuo, @mpbzh, @roalz, @magol, @karalamalar, @zapashcanon, @aishek, @tallesl, @ZeliosAriex, and every other language translation contributors to help me pin down and translate the following sentence in every language: 

> The latest version (0.4.0) is not yet available in #{language} but you can read it in English for now and help translate it.

If you could all post a translation of the above sentence in your respective languages it would be quite useful for me to start improving the way we release new version in the upcoming 0.4.0 version of the manifesto and site. 

Thank you! 🎆

**Comment by Art4** [comment]
German:

Die neuste Version  (0.4.0) ist noch nicht auf Deutsch verfügbar, aber du kannst sie dir auf Englisch durchlesen und bei der Übersetzung mithelfen.

**Comment by magol** [comment]
Swedish 
Den senaste versionen (0.4.0) är ännu inte tillgänglig på #{language}, men du kan läsa det på engelska och även hjälpa till att översätta det.

**Comment by zapashcanon** [comment]
French:

```md
La dernière version (0.4.0) n'est pas encore disponible en français, mais vous pouvez la lire en anglais pour l'instant et aider à la traduire.
```

**Comment by ntrrg** [comment]
Spanish:

Aún no está disponible la última versión (0.4.0) en español, pero por ahora puedes leer en inglés y ayudar con la traducción.

**Comment by aishek** [comment]
Russian:

`Самая последняя версия (0.4.0) ещё пока не переведена на русский, но вы можете прочитать её на английском и помочь с переводом.`

**Comment by tallesl** [comment]
Brazilian Portuguese:

> A última versão (0.4.0) ainda não está disponível em Português mas nesse momento você pode lê-la em inglês e ajudar em sua tradução.

**Comment by roalz** [comment]
Italiano:

L'ultima versione (0.4.0) non è ancora disponibile in Italiano, ma la potete leggere in Inglese per ora e potete contribuire a tradurla.

**Comment by tianshuo** [comment]
简体中文（Simplified Chinese）`最新版（0.4.0）暂时还没有翻译到#{language}，您可以阅读最新的英语版，并且帮助翻译，不胜感激。`
繁体中文(Traditional Chinese) `最新版（0.4.0）暫時還沒有翻譯到#{language}，您可以閱讀最新的英語版，並且幫助翻譯，不勝感激。`

**Comment by ZeliosAriex** [comment]
[es-ES]-> La última versión (0.4.0) aun no está disponible en Español, por ahora puedes leerla en Inglés y ayudar a traducirla.

**Comment by olivierlacan** [comment]
Thanks everybody!
