### ISSUE TITLE
Changelog for internal modifications

### ISSUE THREAD

**Issue by rentalhost** [olivierlacan/keep-a-changelog#163]
Hello, I am working on a project that have "two branches", one is most important to general public (consumers) and another for developers. Currently I write the changelog only for general public, keeping it more friendly, but I like to know about the developers changelog. Should I mix both, split into separated files or then, just ignore it (in this case, the commit message should do the work)?

**Comment by olivierlacan** [comment]
I believe a changelog is relevant to both internal and external users. It seems quite complicated (but understandable) to maintain two changelogs for two different branches. 

In the past I've added `[INTERNAL]` tags to changelog items that were supposed to be parsed out of publicly published parsed changelogs. That of course adds a parsing step and assumes consumers don't have access to the raw changelog (so they won't see `[INTERNAL]` items, if that's even an issue).

If you need to keep the internal changelog completely independent and private then it stands to reason that you could just maintain a separate one but the duplicated work seems like a very specific edge case for your situation. So this is not something I would include in the Keep a Changelog guidelines. 

That said we might add an FAQ item at some point to address this idea of "internal" changes. Although, once again, those are sort of an edge case.

**Comment by Arcesilas** [comment]
Hi,

I'd like to add my questioning about this topic.

In the Changelog guidelines, change types seem to concern more specifically the public API ("_Added for new features_", "_Changed for changes in existing functionality_", etc.).
In the Semver specifications, changes in the "private code" are mentioned ("_Minor version [...] MAY be incremented if substantial new functionality or improvements are introduced within the private code_").
I think there is a lack of consistency.

Maybe the guidelines diserve some clarifications about this question. The FAQ could give indications (not absolute rules) on how to determine which changes or additions diserve to be listed in the changelog, when concerning "private code".

I'm considering this topic more specifically for OSS: users can be developers who use the code (and don't care about internal changes/additions) or developers who contribute (and who care about the architecture of the software.

**Comment by sharkweek** [comment]
Has any more thought been given to adding a FAQ for this issue? I suspect that keeping track of significant changes _between_ releases may be reasonably common for cleaning and updating old code projects.

I'm having this issue on a project I was just given with a bunch of old code that needs to be cleaned and updated. I started a branch that's dedicated to just cleaning up the code. I'm going little by little, editing, testing, and committing just to keep my commits manageable. I'm trying to avoid having one gigantic commit at the end followed immediately by a branch merge.
