### ISSUE TITLE
Migrating all languages to 1.0.0

### ISSUE THREAD

**Issue by olivierlacan** [olivierlacan/keep-a-changelog#164]
Hi folks, [now that 1.0.0 is here](http://keepachangelog.com/en/1.0.0/) I'm looking for your help to port existing language translations. It's not something I can realistically do myself since there was quite a bit of editing involved in this new version so there are paragraphs to rephrase along with some layout changes with the mode from Markdown to Haml to allow greater flexibility for the website.

You can find the source for the English 0.3.0 and 1.0.0 versions here:
- https://github.com/olivierlacan/keep-a-changelog/blob/master/source/en/0.3.0/index.html.haml 
- https://github.com/olivierlacan/keep-a-changelog/blob/master/source/en/1.0.0/index.html.haml

As an example I've already updated French to 1.0.0: 
- https://github.com/olivierlacan/keep-a-changelog/blob/master/source/fr/1.0.0/index.html.haml

Since we've had incredible contributions from you all before, I'll turn on the notification cannon: 👋  @tianshuo, @mpbzh, @roalz, @magol, @karalamalar, @zapashcanon, @aishek, @tallesl, @ZeliosAriex.

I'll be announcing 1.0.0 on my blog very soon with a link to this issue so hopefully we'll get a lot of help from the community as well.

**Comment by zapashcanon** [comment]
I saw a few typo on the french translation, will try to review it soon.

**Comment by Art4** [comment]
I'm working on the german translation.

**Comment by magol** [comment]
I started with the Swedish translation earlier today. I will review it once again tonight, and then it's ready for review by other Swedish speakers.

**Comment by karalamalar** [comment]
tr_TR is done => #165

**Comment by Art4** [comment]
German translation is done, see #167

**Comment by zapashcanon** [comment]
French translation fixed in #169.

**Comment by aishek** [comment]
Russian translation in #170. Great job, Oliver!

**Comment by leocabeza** [comment]
I can work on the Spanish translations.

**Comment by leocabeza** [comment]
I will start `es-ES` today, and I'm hoping to submit the PR before Sunday.

**Comment by azkidenz** [comment]
I'm working on `it-IT` translation.

**Comment by azkidenz** [comment]
#184

**Comment by azkidenz** [comment]
`it-IT` is done #184

**Comment by azkidenz** [comment]
Italian translation fixed #186

**Comment by olivierlacan** [comment]
Since I received a [bit](https://github.com/olivierlacan/keep-a-changelog/issues/178) of [feedback](https://github.com/olivierlacan/keep-a-changelog/pull/191#issue-243268243) about the [Confusing Dates](http://keepachangelog.com/en/1.0.0/#confusing-dates), I just updated it so that 1.0.0 doesn't suffer from a potentially confusing and weak section.

I apologize for this last minute change but I still have some work to do on the responsive CSS for the site so you should all have some time to re-translate this section based on this commit: https://github.com/olivierlacan/keep-a-changelog/commit/c81765b3ea684108637a5a2e657e1c7dfa76c679

**Comment by m-aciek** [comment]
Polish translation in #231.

**Comment by olivierlacan** [comment]
Happy to say, this is done! 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/65950/223321076-1c745b40-dc86-41be-bf66-ad21e6941012.png">
