### ISSUE TITLE
Bug: Section "How can I contribute?" can't be expanded

### ISSUE THREAD

**Issue by Art4** [olivierlacan/keep-a-changelog#173]
If you click the last topic "How can I contribute?" in the [FAQ section](http://keepachangelog.com/en/1.0.0/#frequently-asked-questions) it doesn't expand. This bug exists in the english, german and french version so I think it must be a general bug.

**Comment by olivierlacan** [comment]
Yep, it's a JS bug.

**Comment by olivierlacan** [comment]
Fixed via dc6833e9115f7cb61de753b928781c30b2937958

**Comment by Art4** [comment]
Thanks
