### ISSUE TITLE
Changelog to improvements

### ISSUE THREAD

**Issue by rentalhost** [olivierlacan/keep-a-changelog#175]
Currently we have six types of changelog (added, changed, deprecated, removed, fixed and security), but we haven't "improvement". It is not like a change or added.

For instance:

 * **Added**: added a login panel that uses the user id;
 * **Changed**: moved login panel to first page;
 * **Improvement**: now you can login too via email;

I noted that some users too prefer to use the "improvement" type in cases like that. Then maybe it should be checked.

**Comment by roalz** [comment]
In this specific case, I would consider it "added".
An improvement is either something added or changed, and as I think that the final target for a change in a product is to make it better (= improve it), "improvements" are implicitly listed ad additions or changes.
