### ISSUE TITLE
"Confusing dates" paragraph could be better

### ISSUE THREAD

**Issue by callumlocke** [olivierlacan/keep-a-changelog#178]
> #### Confusing Dates
>
> In the U.S., people put the month first (06-02-2012 for June 2nd, 2012), while many people in the rest of the world write a robotic-looking 2 June 2012, yet pronounce it differently. 2012-06-02 works logically from largest to smallest, doesn't overlap in ambiguous ways with other date formats, and is an ISO standard. Thus, it is the recommended date format for changelogs.

This is vaguely contentious for no apparent reason. Why "robotic-looking"? And I'm not sure what it means by "yet pronounce it differently". Most people in my country pronounce dates in that order (day then month).

IMO this paragraph should just state that ISO 8601 dates are recommended for changelogs because they are unambiguous.

**Comment by magol** [comment]
I completely agree.
When I translated into Swedish, I simply ignored this because it does not mean anything. For us in Sweden it is not robotic-looking, and we pronounce it as it says.

So I absolutely think it should be removed.

**Comment by olivierlacan** [comment]
@magol While I appreciate your opinion, I'd like for translations to reflect the original version. :-)

@callumlocke Good idea, can you submit a PR with your suggestions?

**Comment by magol** [comment]
@olivierlacan Overall, I absolutely agree with you. I always try to reflect the original text when I translate. But sometimes you have to do some sort of localization so that the text works in the new context.
If it is obvious that it is a translated text, you have failed as a translator.

**Comment by olivierlacan** [comment]
@magol See: c81765b

> Regional date formats vary throughout the world and it's often difficult to find a human-friendly date format that feels intuitive to everyone. The advantage of dates formatted like <code>2017-07-17</code> is that they follow the order of largest to smallest units: year, month, and day. This format also doesn't overlap in ambiguous ways with other date formats, unlike some regional formats that switch the position of month and day numbers. These reasons, and the fact this date format is an [ISO standard]("http://www.iso.org/iso/home/standards/iso8601.htm") are why it is the recommended date format for changelog entries.
