### ISSUE TITLE
Drop-down menu broken/empty in Firefox

### ISSUE THREAD

**Issue by JonathanWillitts** [olivierlacan/keep-a-changelog#180]
The drop-down menu (for the selection of language/version) at the top right of the site appears to be broken in Firefox.  

## Behaviour
- As the site loads, the drop-down itself has no text in it.
- Clicking on the drop-down, expands it to a list of blank entries. 
- Clicking on any of the blank entries DOES take you to another language/version.  

This behaviour was experienced on:
- Firefox 54 (Ubuntu)
- Firefox 54 (Windows)

The drop-down menu seems to work fine in IE 11 </shudders>

**Comment by dgdavid** [comment]
It seems to be a bug (quite old bug, 17 years old) in Gecko engine, as is stated  in the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) and gathered in the [bugzilla issues tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=40545).

The solution is to use the label's content as content for the option itself.

I'll fix it and make a PR.
