### ISSUE TITLE
Isn't a CHANGELOG about all changes not just important changes?

### ISSUE THREAD

**Issue by olivierlacan** [olivierlacan/keep-a-changelog#2]
Several interesting comments on Twitter from Caleb Thompson and Aaron Patterson. 

> [Caleb Thompson](https://twitter.com/thompson_caleb/status/481485964162785280): @olivierlacan That’s exactly a changelog. NEWS is a record of changes between releases, which is what you want. http://t.co/bneYwnliy3
> 
> [Caleb Thompson](https://twitter.com/thompson_caleb/status/481486279847051264): @olivierlacan NEWS is for important changes, not every change as a log of changes would be.
> 
> [Caleb Thompson](https://twitter.com/thompson_caleb/status/481509770315067392): @olivierlacan  Here, have some more. https://t.co/BCggwhnJnr https://www.gnu.org/prep/standards/html_node/NEWS-File.html#NEWS-File https://www.gnu.org/prep/standards/html_node/Change-Logs.html
> 
> [Aaron Patterson](https://twitter.com/tenderlove/status/481497256332230656) @mperham end user focused changes should be in NEWS.

I think the GNU standards are definitely something this project will have to take into account. I do have an initial dislike for the NEWS file idea because of its atrocious semantics. NEWS tells me much less about the purpose of this file than CHANGELOG does. And its focus is not obvious at all, which I believe should explain why there's so much confusion around the naming of end-user focused change logs.

<sarcasm>It also wouldn't be the first time people from the GNU community commit semantic crimes. </sarcasm> Another proof that — yes — naming does matter, a lot.

**Comment by darkfeline** [comment]
I think there's a misunderstanding here between change logs and release notes (`NEWS`, `RELEASE`).

Change logs are indeed for storing all changes. I believe this dates back to when wonderful version controls like Git did not exist. In such a world, keeping a list of all changes is very useful, hence the existence of the change log. I refer to the [GNU documentation on change logs](https://www.gnu.org/prep/standards/html_node/Change-Logs.html), which clearly expresses this intent.

Release notes, on the other hand, are what Keep a Changlog is really trying to be. I refer to the [GNU documentation on NEWS files](https://www.gnu.org/prep/standards/html_node/NEWS-File.html) and [Wikipedia](https://en.wikipedia.org/wiki/Release_notes).

Now that we have good version control tools, I agree that it's a good idea to retire the ChangeLog file and agree on naming release notes as either NEWS or RELEASE (with some standard extension). I don't think trying to forcefully redefine "change log" is a good idea however.

**Comment by vxcamiloxv** [comment]
I know that the intention of the `keep-a-changelog` are good and quite necessary, After reading a couple about this, and after almost 5 years using the `CHANGELOG` way, I think ends up being more like the old 'ChangeLog`, pretty verbose and in big projects not pretty human readable and useful, for example: https://github.com/nodejs/node/blob/master/CHANGELOG.md, github release notes become more readable and closer to the old NEWS file https://github.com/nodejs/node/releases, also the old `NEWS` files have been using for more than 25 years for projects such as Gimp/Gnome so is a example of success for long time using the `NEWS` files,  is not necessary reinvent the wheel.

After 6 years of this issue for me `Isn't a CHANGELOG about all changes not just important changes?
` question still open, for example rust keep an [CHANGELOG](https://github.com/rust-lang/rust/blob/master/src/tools/clippy/CHANGELOG.md) for sub-projects but in the main one it have [RELASE](https://github.com/rust-lang/rust/blob/master/RELEASES.md) file and seems to me that the RELEASE file is for important things and the CHANGELOG for more generic ones
