### ISSUE TITLE
Idea: Open source CHANGELOG editor

### ISSUE THREAD

**Issue by beam2web** [olivierlacan/keep-a-changelog#210]
Is it possible for you to build an online editor (WYSIWYG) with your rules or like a kind of todo list:
http://rncoverletter.net/wp-content/uploads/2017/06/free-printable-to-do-list-todo-list-fitmaxw800.png / https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Web_Platform/5/html/Seam_Reference_Guide/images/todo.png

- [ ] configuration of possible types like your definitions (config should stored in a JSON / XML - File)
-- Added
-- Changed
-- Deprecated
-- Removed
-- Fixed
-- Security
-- ...

- [ ] configuration of Icons (like fontAwesome) for each type like https://www.mozilla.org/en-US/firefox/52.0/releasenotes/
- [ ] import for CHANGELOG.md and check against your rules
- [ ] export for CHANGELOG.md / CHANGELOG.html / CHANGELOG.pdf
- [ ] Maybe other nice things :)

**Comment by olivierlacan** [comment]
Good luck with that, but this project is not meant to focus on tools.
