### ISSUE TITLE
Offer option to download the example changelog file

### ISSUE THREAD

**Issue by kbabioch** [olivierlacan/keep-a-changelog#212]
Maybe I've missed something on the website, but I couldn't find a link to easily download the proposed Changelog example. I rather had to copy & paste it, which isn't too comfortable, since there is a lot of text to scroll through, etc. Offering a link to download a plain text copy would make things easier.

**Comment by olivierlacan** [comment]
Good idea. Can you submit a Pull Request to add this feature to the English 1.0 version?

**Comment by kbabioch** [comment]
I'm not familiar with Ruby & Co., so it is probably faster if you just add the link, rather than me trying to figure out where stuff needs to be put ;).

**Comment by olivierlacan** [comment]
Link was added.
