### ISSUE TITLE
changelog formats do not match

### ISSUE THREAD

**Issue by shoulders** [olivierlacan/keep-a-changelog#217]
the changelog format is shown in several places

- the downloadable code in v1.0.0
- the CHANGELOG.md file https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md
- http://keepachangelog.com/en/1.0.0/

the 3 are not the same.

- in the downloadable file v1.0.0 and the keepachangelog page there is a UNRELEASED tag at the top and then one at the bottom with loads of comparison links but in CHANGELOG.md in the repo there is only an UNRELEASED tag at the top. Which should be used?
- in the keepachangelog page and the repo CHANGELOG.md have one version of the blurb at the top of the changelog with the links poiting to particular version of the change log and semantic versioning but the downloadable file v1.0.0 has the same links but do not point to particular versions. which should be used.
````
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html).

````
and
````
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/)
and this project adheres to [Semantic Versioning](http://semver.org/).
````

These differences need to be changed so they are all the same.

thanks

**Comment by olivierlacan** [comment]
This has been fixed for a while. The shown changelog is now dynamically the actual changelog.
