### ISSUE TITLE
Sections should be only recommended

### ISSUE THREAD

**Issue by OndraM** [olivierlacan/keep-a-changelog#22]
Inspired by #20, I would now say the possible sections for each release (like Added, Deprecated, Removed etc.) should be only recommended by the formal specification.

Each project works differently. For example someone would never use Security sections. while [someone](https://github.com/angular/angular.js/blob/master/CHANGELOG.md) always use Performace section. Instead of trying to list all possible section, I would suggest only list few mainly used sections, mention these are only examples, and let anyone chose those sections that fits the specific project.

**Comment by lunemec** [comment]
I suggest having *some* sections required - and be empty if there are no changes, but the format should be plastic enough to allow for "custom" tags/sections.

I agree with @olivierlacan when you leave people with choice, they will not read documentation properly or misunderstand and will use it wrong. Like jusing **just** *Changed* section and nothing else.

**Comment by mockturtl** [comment]
https://github.com/olivierlacan/keep-a-changelog/issues/44#issuecomment-99618905

**Comment by olivierlacan** [comment]
I've gone back and forth on whether Keep a Changelog should push for empty categories when nothing has changed. The absence of change has value, especially when scanning releases.
