### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by u2berggeist** [olivierlacan/keep-a-changelog#222]
In the last paragraph, it says:

>These reasons, and the fact this date format is an ISO standard are why it is the recommended date format for changelog entries.

It is missing a comma after standard, so it should be: **,**

>These reasons, and the fact this date format is an ISO standard, are why it is the recommended date format for changelog entries.

I'm sure there are other ways to fix it, but this is just the one that I though of.

**Comment by olivierlacan** [comment]
Can you submit a pull request with this change?

**Comment by pboling** [comment]
@olivierlacan PR https://github.com/olivierlacan/keep-a-changelog/pull/224
