### ISSUE TITLE
Present type of changes in relation to semver

### ISSUE THREAD

**Issue by c8y3** [olivierlacan/keep-a-changelog#226]
I would find it interesting to somehow present types of changes in relation to semver, since it seems to me that:
* Changed and Removed are only allowed in major,
* Added and Deprecated in minor or major,
* Fixed and Security in any version

I don't know how easy this is to do, but you could present the types of changes, sorted from most disruptive to the less important ones.
And then have 3 lines with different colors in the margin (red for major, blue for minor and green for patch). The red line would go all the way, the blue line would cover 2 third of the list and the green line only the last third.

I hope I could make myself understood...

**Comment by reedstrm** [comment]
This sort of thinking helps with the developers dilemma "what should the next version number be?" And combines nicely with the "keep an UNRELEASED section" advice. It allows for easy scanning of that section when adding the actual release number: "oh right, we committed that API change this month, need to go with a major version bump" vs. "hmm, bunch bug fixes, we're good with patch" In fact, this makes the CHANGELOG the first stop for making the version call. If you're using some sort of enforced CHANGELOG entries per PR approach, it might be the only stop needed.

**Comment by mvz** [comment]
I would look at this the other way as well, in that this may help make it clear what is meant by, e.g., Changed vs Fixed. So Changed is a *breaking* change to functionality, whereas Fixed is a change that fixes or improves functionality.

OTOH, why not make this clearer for the *reader* of the changelog, and have headings that directly relate to SemVer terminology, like, say, 'Breaking Changes', 'New Functionality', and 'Bug fixes'?

**Comment by mvz** [comment]
Oh, I see there is already a discussion about this in #41.
