### ISSUE TITLE
Giving credit to contributors

### ISSUE THREAD

**Issue by smitchell556** [olivierlacan/keep-a-changelog#227]
The changelog for this project uses @<contributor> to give credit to contributors, but this isn't referenced on the website. Changelogs for other projects use PR numbers instead. Is there a preferred way or could one or the other be used?

**Comment by olivierlacan** [comment]
That’s a good question. @references do not trigger links to be created on GitHub as far as I know. Neither do PR numbers unless you manually link them. Although I’m not sure on the latter. PR links can be useful for end users to understand the context, ramifications, and details of a summarized change. In that way they feel more useful. 

But there’s definitely a good community aspect to recognizing contributors by name (or handle) in changelogs. I think both are fine and achieve different goals.


On January 29, 2018 at 21:04:38, Spencer Mitchell (notifications@github.com) wrote:

The changelog for this project uses @ to give credit to contributors, but this isn't referenced on the website. Changelogs for other projects use PR numbers instead. Is there a preferred way or could one or the other be used?

**Comment by smitchell556** [comment]
That pretty much sums up how I feel about it, although I wasn't sure if one way was preferred over the other. Thanks for the input.
