### ISSUE TITLE
Should non-GitHub projects have an Unreleased section?

### ISSUE THREAD

**Issue by Stevoisiak** [olivierlacan/keep-a-changelog#236]
The example `CHANGELOG.MD` file includes an *Unreleased* section which links to a list of [commits made since the last release](https://github.com/olivierlacan/keep-a-changelog/compare/v1.0.0...HEAD). This follows the [guiding principle](https://keepachangelog.com/en/1.0.0/#how) that:

> Versions and sections should be linkable.

Does this guiding principle apply to offline projects that aren't hosted on GitHub?

For example: I have an unreleased desktop application that is currently hosted offline, which makes it difficult to follow this guideline.

Since the project is hosted offline where summary links aren't possible, should an *Unreleased* section be included?

**Comment by olivierlacan** [comment]
Unreleased doesn’t have much to do with GitHub. It’s a catch-all section for any upcoming change. Whether your project is hosted on GitHub, your laptop, or some remote private server, the changelog is a document of your notable changes at this point in time. If you intended on keeping a changelog I’d keep the section around as a reminder that:

- you have to document notable changes as you make them not just at the end
- when the unreleased section gets a bit too long it might be time for a release

Don’t underestimate the value of empty folders and empty sections. Just like the empty sections that denote no changes of a certain type (Removed, Deprecated), the Unreleased section has a psychological effect on maintainers themselves, not just the people who consume the changelog in the end.

**Comment by olivierlacan** [comment]
To summarize. We may need to update this line to add « if possible ».
