### ISSUE TITLE
Platform agnostic version links

### ISSUE THREAD

**Issue by aryelgois** [olivierlacan/keep-a-changelog#249]
Hey, just a small question:

I am using links in the versions to point to github's compare, just like in this repository.

But they get useless if the project migrates to another platform (bitbucket, gitlab, etc)

What can I do?

It would be awesome if keep-a-changelog got really big and these platforms processed the changelogs to replace the links to their own site, when viewing the rendered markdown..

**Comment by oxr463** [comment]
Any updates on this?

**Comment by oxr463** [comment]
# GitLab

https://gitlab.com/{{namespace}}/{{project}}/-/compare/master...master

**Comment by aryelgois** [comment]
# Bitbucket

```markdown
[unreleased]: https://bitbucket.org/{{namespace}}/{{repository}}/branches/compare/HEAD..{{version}}

[{{version}}]: https://bitbucket.org/{{namespace}}/{{repository}}/branches/compare/{{version}}..{{previous_version}}
```
