### ISSUE TITLE
No clear separatio between updates

### ISSUE THREAD

**Issue by schroef** [olivierlacan/keep-a-changelog#259]
Ive been looking at this changelog update style and i really like it a lot. It so much easier to maintain a changelog using this setup compared to the tabel version of github.

The only thing i dont like is that there is not a clear separation between each update. Im a graphic design and i look at these kind of thing. The spacing in between each update is the same as a regular paragraph, therefor it looks like one big list. Perhaps its better to add a more clear separation of paragraphs. Im not sure how this can be done. Perhaps the thin line or extra spacing at the end, but i think such thing cant be done

**Comment by lioman** [comment]
You just can add one of these (But I would omit the asterisks as a valuable option):
```
---
----------
- - - - - - - - - -
***
* * *
* * * * * * * * * *
___
__________
_ _ _ _ _ _ _ _ _ _
```

Which translates to:

---

**Comment by schroef** [comment]
Sorry for the late reply, thanks for the info.

So essentially what every a user wants.

**Comment by olivierlacan** [comment]
I think the visual separation is fine as it is with basic Markdown paragraph spacing, but you're free to add more if you think it's needed.
