### ISSUE TITLE
[SOLVED] How do you add the compare link for version

### ISSUE THREAD

**Issue by schroef** [olivierlacan/keep-a-changelog#260]
I notice that with each version you add a link to the compate page, yet i think that page is one complte chaos.

One other thing, you have version 0.0.2 and it links to a compate page. Yet when i try to find that, there is no 0.0.2 version

**Comment by JohnRGee** [comment]
The compare link for the version is an URL which configures GitHub [compare](https://help.github.com/articles/comparing-commits-across-time/) to see the difference between two states of the repository. You can either copy and edit a previous URL with the new tags, or set up the compare in the browser using the compare page itself and then copy the URL.

**Comment by schroef** [comment]
Thanks, you other answer helped me already

👍
