### ISSUE TITLE
[SOLVED] [Q] How do the version tags automatically link to the tags

### ISSUE THREAD

**Issue by schroef** [olivierlacan/keep-a-changelog#261]
Im trying this new method and also applying the versioning tags like you show in the changelog. Ive applied tag using sourcetree but they dont link automatically as yours does. When i look in the branch section i do see the tags but they dont turn blue. Im not sure i even like this because its quite a messy overview, i hardlt understand that part. Learning github and cloud backup is really intense, seems like a ton of work

**Comment by schroef** [comment]
In the latest release its also stated 'Links to latest released version in previous versions.' I dont see hardcoded links, how is github making these links?

**Comment by JohnRGee** [comment]
The versions in the section titles are using a markdown feature called reference links, where the link label and the URL are defined separately. Since the version itself can be used as the label, it is using the shortcut reference link style.

<https://spec.commonmark.org/0.28/#shortcut-reference-link>

**Comment by schroef** [comment]
Thanks, but when i look at the raw code of the changelog.md in this repo it doesnt show these link after the version. Yet they do work as links?

My guess is because they have been using branches as well. Im working in a master branch only but do have tags assigned. My guess now these links are generated automatically when branches are used.

<img width="726" alt="screen shot 2018-10-01 at 16 31 08" src="https://user-images.githubusercontent.com/6923008/46314104-a132e180-c597-11e8-82b0-4ca77080b1cc.png">

PS i jsut noticed at the bottom it also shows something which does look like the example you've linked. Probably this is cause it than

<img width="725" alt="screen shot 2018-10-01 at 16 33 54" src="https://user-images.githubusercontent.com/6923008/46314207-ec4cf480-c597-11e8-872d-acc666927492.png">

**Comment by JohnRGee** [comment]
My previous comment was explaining how the version "tags turn blue", which is the markdown. Yes, the URLs are all down the bottom of the CHANGELOG as in your screenshots.

As for how you construct the URL to put for the link (copied from#260):

The compare link for the version is an URL which configures GitHub compare to see the difference between two states of the repository. You can either copy and edit a previous URL with the new tags, or set up the compare in the browser using the compare page itself and then copy the URL.

**Comment by schroef** [comment]
Yes i know, i didnt noticed their links at the bottom. Also i would not think that they would refer to the links scattered all over the document and would be working.

I just test it with my own files and it works, nice :)

Thanks for the info!
