### ISSUE TITLE
Should you ever rewrite things you put in your CHANGELOG before?

### ISSUE THREAD

**Issue by Zegnat** [olivierlacan/keep-a-changelog#28]
Basically, should CHANGELOG files be `diff`able to quickly see what updates have been added since the last time? I just ran into a diff that made little sense (i.e. it had not just prepended new information to the top): [CHANGELOG.txt, Zegnat/AdBlock-WebKit@2842332](https://github.com/Zegnat/AdBlock-WebKit/commit/28423322f2e92f97f52d2ac071bf83e75ecff23a#diff-a0493e27f48b50e18312b9f4508fc29d).

**Comment by lunemec** [comment]
:+1:

**Comment by olivierlacan** [comment]
Closed via 46da84292d1475e8f50c97fd4137b432e46b5f29
