### ISSUE TITLE
semver: v0.0.1 is not valid initial release

### ISSUE THREAD

**Issue by LucidOne** [olivierlacan/keep-a-changelog#286]
This is pedantic, but since keep-a-changelog is supposed to be a reference...

Based on my reading of the [semver spec](https://semver.org/spec/v2.0.0.html) the initial version [v0.0.1](https://github.com/olivierlacan/keep-a-changelog/tree/v0.0.1) as this maps to
```
MAJOR = 0
MINOR = 0
PATCH = 1
```
SemVer states that "PATCH version when you make backwards-compatible bug fixes." and the initial release is not a bug fix. More explicitly the [FAQ](https://semver.org/spec/v2.0.0.html#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) suggests starting at `0.1.0`.
Though personally I think version `0.0.0` would also be a vaild SemVer initial release.

Since actually fixing this is a waste of time, I wonder if this could be a note in the FAQ/Docs about "Initial Changelog"

**Comment by olivierlacan** [comment]
I don't think it's a waste of time to fix it but I don't know how we would since 0.0.1 and 0.1.0 are both versions and I don't think it's a good idea to replace one version (0.1.0) with a completely different version. But maybe somebody will have a suggestion.

**Comment by nnmrts** [comment]
Well, this may sound radical, but why not make it a breaking change?

It's really weird how meta this is tho. But I think, if we just

- separate this project's changelog from the website,
- then create a new "example changelog"
- then add it to the website with a disclaimer above it like "this is an example changelog"
- then release keep-a-changelog under version 2.0.0

While this is the best option to choose in my opinion, we could also just

- remove (or replace) the "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)" line, treating it as a bugfix (which would also be a breaking change I guess...)
- then merge the branch [x-ver](https://github.com/olivierlacan/keep-a-changelog/tree/x-ver)
- then release keep-a-changelog under version 2.0.0 (or 1.1.0 if you don't consider this a breaking change)

@olivierlacan what do you think about this?

**Comment by nnmrts** [comment]
Wait a second.

Since the keep-a-changelog changelog only says 

> The format is **based** on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)

we **don't** have a weird meta loop here. Since the Keep a Changelog changelog is only "based" on Keep a Changelog, my suggested changes from the comment above wouldn't be breaking.

My brain hurts.

**Comment by olivierlacan** [comment]
Yep, this is not worth the effort. Sorry. 😅
