### ISSUE TITLE
Version discrepancy between website documentation and release

### ISSUE THREAD

**Issue by isuftin** [olivierlacan/keep-a-changelog#298]
Website documentation shows that the current version of Keep A Changelog is 1.1.0.

Latest release seems to be 1.0.0 and there is no cangelog documentation for 1.1.0

![image](https://user-images.githubusercontent.com/928288/55645877-5a6cb100-579f-11e9-8a85-4fc037a5caeb.png)

**Comment by cschroed-usgs** [comment]
Potentially relevant commit:
https://github.com/olivierlacan/keep-a-changelog/commit/3a7298570a6c3887a8038204213c8673f6079a78

**Comment by isuftin** [comment]
Removing this issue since the official page references 1.0.0 at this time
