### ISSUE TITLE
Add more GitHub topics

### ISSUE THREAD

**Issue by dominiksalvet** [olivierlacan/keep-a-changelog#304]
Hi! I would like to propose adding more GitHub topics, which can also help people to find this repository. These are the topics I have considered: [`history`](https://github.com/topics/history), [`tag`](https://github.com/topics/tag), [`versioning`](https://github.com/topics/versioning), [`release`](https://github.com/topics/release), [`semver`](https://github.com/topics/semver) and I also wouldn't be scared of adding the general ones: [`markdown`](https://github.com/topics/markdown) and [`git`](https://github.com/topics/git). What do you think?

**Comment by dominiksalvet** [comment]
Please, can anyone take a look at this issue. It's really simple to solve and it can bring more people to the project.

**Comment by qeef** [comment]
Think this is good point.

**Comment by olivierlacan** [comment]
Sorry @dominiksalvet. I'll fix that right away. Thanks for your suggestions. :-)
