### ISSUE TITLE
command 'extension.runMatlab' not found

### ISSUE THREAD

**Issue by COCO5666** [olivierlacan/keep-a-changelog#311]
Open the command palette (with shortcut ctr+shift+p) and run the "Run Matlab File" command.

command 'extension.runMatlab' not found
![image](https://user-images.githubusercontent.com/36597804/63216700-e3dbb900-c16b-11e9-9299-7f18f3fcaf70.png)

**Comment by olivierlacan** [comment]
I don't think you're asking this in the right place.
