### ISSUE TITLE
Provide an actual "getting started" example of how keep-a-changelog works.

### ISSUE THREAD

**Issue by gregkrsak** [olivierlacan/keep-a-changelog#314]
It is not clear, within the first 15 seconds of scanning the README, how this project *actually* is used.

A "getting started" demonstration---either in text, animated GIF, video, or whatever---would be nice.

This example should be very accessible, and start educating a first-time repository visitor within 15 seconds of finding the project.

**Comment by olivierlacan** [comment]
There's nothing to get started on, this project generates a website: https://keepachangelog.com/en/1.0.0/

The website offers guidelines and suggestions. That's about it. 😃

**Comment by gregkrsak** [comment]
Oh.


Even *that* wasn't clear. ;)

Thanks.

**Comment by olivierlacan** [comment]
Did you read the README?  

Because it’s explained in the second four word sentence.

**Comment by gregkrsak** [comment]
I did.

I just never considered the possibility where that's *all* it does.

People are browsing much more "significant" repos, then they come along to
this one, and it can be confusing that all it does is generate a website.

**Comment by Knowledge-Wisdom-Understanding** [comment]
I agree with @gregkrsak . The Readme is not very  clear what exactly the project does. Yes it generates https://keepachangelog.com/. , but what exactly does that mean? Does it take all your commits from any repo that you run it in and create a nice changelog for you in the browser or does it do nothing more than open up keep-a-changelog's changelog in the browser on localhost. I'm going to assume the former as the latter would be utterly pointless. Kind of ironic how vague this projects readme is considering it's a project dedicated to more concise/informational source control changelogs.

**Comment by olivierlacan** [comment]
Likely addressed via bb9539b
