### ISSUE TITLE
Ensure the recommended change log template passes markdownlint

### ISSUE THREAD

**Issue by MOZGIII** [olivierlacan/keep-a-changelog#317]
`markdownlint` is a neat tool, but the change log template doesn't seem to pass with the default settings.
Can we somehow make it so that when I copy the template to start the change log in my project `markdownlint` doesn't complain?

**Comment by bhrutledge** [comment]
A search of the issues turned #274, which has lots of discussion (that I haven't read).

**Comment by MOZGIII** [comment]
Thx
