### ISSUE TITLE
Typo on the "what about yanked releases" tab

### ISSUE THREAD

**Issue by nedtwigg** [olivierlacan/keep-a-changelog#327]
On https://keepachangelog.com/en/1.0.0/

<img width="552" alt="Screen Shot 2020-01-11 at 1 31 34 PM" src="https://user-images.githubusercontent.com/2924992/72210876-ba069400-3476-11ea-9160-bce6482d5d7d.png">

```
## 0.0.5 - 2014-12-13 [YANKED]    <-- how it is
## [0.0.5] - 2014-12-13 [YANKED]  <-- how it should be (I think)
```

**Comment by olivierlacan** [comment]
Do you mind making a pull request to address this?

**Comment by nedtwigg** [comment]
I just did a dumb find-replace across the whole project.  Dunno if there's more to it than that.
