### ISSUE TITLE
No suggestions for handling changes in dependencies

### ISSUE THREAD

**Issue by masukomi** [olivierlacan/keep-a-changelog#33]
Let's say you have an app that's dependent upon some external service or library. That external software has been updated and you have leveraged the latest version of it in your app, thus giving your app new features or limitations.

When producing a change log for your app it seems that the most responsible, and sensible, thing to do would be to point out the changes in the external software that are applicable to yours... 

Maybe a "Changes from External sources" section or a suggestion for a convention for linking to external repos / web sites for changes. 

The best would be a way to link to the markdown changelog from an external project such that if it was using the keep-a-changelog format we'd be able to programmatically ingest the changes from the linked version  eg 

```
## Additions
  - blah
  - blah
  - Added changes from [version 0.0.2-0.0.4 of keep-a-changelog](https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/gh-pages/CHANGELOG.md)
```

That would (potentially) enable a script to see that the link is to a `CHANGELOG.md` file and parse it to extract the changes in versions between 0.0.2 and 0.04  for insertion into the rendered version of your change log.

**Comment by lunemec** [comment]
What about:

## [0.0.6] - 2014-12-12
### Dependencies
- project-name [0.0.2] -> [0.0.3]
- keep-a-changelog [0.0.1] -> [0.0.2]

**Comment by elyscape** [comment]
The only possible issue with that would be a potential collision between link names.  One way would be to make sure to name them differently, like so:
```markdown
## [0.0.6] - 2014-12-12
### Dependencies
- project-name [0.0.2][project-name-0.0.2] -> [0.0.3][project-name-0.0.3]
- keep-a-changelog [0.0.1][keep-a-changelog-0.0.1] -> [0.0.2][keep-a-changelog-0.0.2]

[project-name-0.0.2]: http://example.com/project-name/releases/0.0.2
[project-name-0.0.3]: http://example.com/project-name/releases/0.0.3
[keep-a-changelog-0.0.1]: https://github.com/olivierlacan/keep-a-changelog/releases/tag/v0.0.1
[keep-a-changelog-0.0.2]: https://github.com/olivierlacan/keep-a-changelog/releases/tag/v0.0.2
```

**Comment by lunemec** [comment]
In this case, we can drop the version in brackets, its superfluous, and just leave the version in the project name.

    ## [0.0.6] - 2014-12-12
    ### Dependencies
    - project-name [project-name-0.0.2] -> [project-name-0.0.3]
    - keep-a-changelog [keep-a-changelog-0.0.1] -> [keep-a-changelog-0.0.2]

    [project-name-0.0.2]: http://example.com/project-name/releases/0.0.2
    [project-name-0.0.3]: http://example.com/project-name/releases/0.0.3
    [keep-a-changelog-0.0.1]: https://github.com/olivierlacan/keep-a-changelog/releases/tag/v0.0.1
    [keep-a-changelog-0.0.2]: https://github.com/olivierlacan/keep-a-changelog/releases/tag/v0.0.2

**Comment by elyscape** [comment]
> On the side note, how did you color it?? :D

[Code fences!](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)

    ```markdown
    markdown code goes here
    ```

**Comment by cdeszaq** [comment]
:+1: I think this is a clean way of handling dependency changes and links to the relevant places to see the differences as best as those dependencies have them.

**Comment by olivierlacan** [comment]
You used the word "change". We have a section named `Changed`. I think your answer is obvious.
