### ISSUE TITLE
Easy Download of Template

### ISSUE THREAD

**Issue by ChrisBeeson** [olivierlacan/keep-a-changelog#331]
I like the idea, but I was confuffled that there was no easy or obvious template to download.

Plus if you try to select the example text on the website with apple or control + a, it selects the whole website.... think this is an obvious shortcoming!

**Comment by DianaNites** [comment]
I was confused by this exact thing!

For a project that "aims to be a better changelog convention", it sure doesn't document that convention anywhere.. I wanted to start keeping a proper changelog and use this standard, but there is no standard?

**Comment by salimregragui** [comment]
click on the file CHANGELOG.md, click on edit the file. And there you go you got your template ready to be used.

**Comment by rdeago** [comment]
> click on the file CHANGELOG.md, click on edit the file. And there you go you got your template ready to be used.

You also got your own automatically created fork of the project, which you maybe didn't want.

**Comment by Rabadash8820** [comment]
Rather than clicking edit on CHANGELOG.md, you can just click the `Raw` button. That gives you access to the raw Markdown text, without creating a fork.

**Comment by Linux-cpp-lisp** [comment]
Bumping this issue — it would be really nice to have a simple empty template so that you don't need to go through deleting old info about this repo when trying to add a changelog to a new project.

**Comment by olivierlacan** [comment]
I'm going to close this, anyone is welcome to contribute something that either makes it more obvious that the version number shown on the website links to the example version shown, display a more clear download button.

I think the link showing the version and allowing anyone to download via the action buttons is a fine compromise in the meantime: 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/65950/223606951-db41f473-3047-4557-aad1-267ef504a43a.png">
