### ISSUE TITLE
Website does not show 1.1.0

### ISSUE THREAD

**Issue by Nixinova** [olivierlacan/keep-a-changelog#352]
The homepage at keepachangelog.com redirects to /en/1.0.0/ even though 1.1.0 was released over a year ago. 1.1.0 does not appear in the changelog textarea on the website as well even when you manually navigate to /en/1.1.0/. The navigation drop-down also does not show 1.1.0.

**Comment by Siilwyn** [comment]
This is a duplicate of https://github.com/olivierlacan/keep-a-changelog/issues/320
