### ISSUE TITLE
Unreleased tied to specific releases

### ISSUE THREAD

**Issue by kirkmadera** [olivierlacan/keep-a-changelog#367]
I think the Unreleased section should be tied to specific upcoming releases.

We maintain projects that have multiple long term supported major releases that may continue to have features added to them and minor releases that may have a number of bugs fixed over time before actually releasing.

It's helpful to show the features and bugfixes that are upcoming across multiple releases. 

To that note, we are currently using this format:

    ## [1.2.0] - Unreleased
    ### Added
    - New feature A
    - New feature B
    
    ## [1.1.1] - Unreleased
    ### Added
    - Bugfix A
    - Bugfix B
    
    ## [1.1.0] - 2020-08-01
    ### Added
    - Feature A
    - Feature B
    - Bugfix A

**Comment by jkour** [comment]
And what do you do if BugfixA does not make it in release 1.1.1 but in 1.2.0?

**Comment by kirkmadera** [comment]
We add this to the changelog as the fixes/bugs are applied, but not actually release the version until there is enough fixes in place to be worth releasing or there is a specific project motivating a release. Also, being unreleased, it's reasonable that this changes anyways if you did need to move something around.

**Comment by kirkmadera** [comment]
I thought about this further and this feels worthy of a separate ROADMAP.md file. I think it makes more sense to keep CHANGELOG.md to historical changes and ROADMAP.md to upcoming changes. Potentially, this project should also define the same/similar format for a roadmap as I don't see a standard for that.
