### ISSUE TITLE
Some links are outdated

### ISSUE THREAD

**Issue by edukisto** [olivierlacan/keep-a-changelog#404]
At the moment,

- <http://www.iso.org/iso/home/standards/iso8601.htm> is being redirected to <https://www.iso.org/iso-8601-date-and-time-format.html> (note the URL scheme);
- <https://help.github.com/articles/creating-releases/> is being redirected to <https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository>.

**Comment by dolmen** [comment]
This issue should be 301, not #404. 🤣

**Comment by olivierlacan** [comment]
Fixed via 08ec13036397747247c581f9b615c387720f9549
