### ISSUE TITLE
keepachangelog.com website broken

### ISSUE THREAD

**Issue by malachid** [olivierlacan/keep-a-changelog#424]
I was noticing today that `https://keepachangelog.com/en/1.0.0/` was broken. It said the problem was that github was down.  The `status.github.com` page referenced on that page no longer loads, but the status at the bottom of this page goes to `https://www.githubstatus.com/` which says everything is fine.  I also noticed that `https://keepachangelog.com` was reporting the same problem.

The chrome console inspector says that it is due to 503 errors.
![screenshot](https://user-images.githubusercontent.com/396197/155173731-6ec83296-e7a9-4ec2-b082-24b20441ce1d.png)

**Comment by olivierlacan** [comment]
This was likely a transient issue due to GitHub Pages (how KAC is hosted) downtime
