### ISSUE TITLE
ERROR:  Error installing redcarpet:

### ISSUE THREAD

**Issue by bbethell-1** [olivierlacan/keep-a-changelog#426]
ERROR:  Error installing redcarpet:
	ERROR: Failed to build gem native extension.

    current directory: /home/bbethell/.local/share/gem/ruby/gems/redcarpet-3.5.1/ext/redcarpet
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20220303-265039-gvawm9.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

**Comment by olivierlacan** [comment]
Please look for Ruby debugging help either on Redcarpet's repo or with your Ruby version manager of choice. 😃
