### ISSUE TITLE
Awesome guide! + Suggestions/Ideas

### ISSUE THREAD

**Issue by mbrand12** [olivierlacan/keep-a-changelog#44]
This is a great guide. I was just looking for some rules since every time I
attempted to keep a change log for my own use it ended up being totally useless

In respect to the earlier releases it might be a good idea to order the sections
within a change log to first display those more crucial to those "less" crucial.

So something like:
- Security
- Fixed
- Removed
- Deprecated
- Changed
- Added

Also it might be a good idea to make the README more detailed for those (like
me) who are beginners but want to use this and make a habit out of it. Thought I
guess consistency is more important whatever the order is.

So a little bit more detail about "what" should go under these sections using
some real project examples. For example, does a removed method go into the
Removed section or Changed section? What does Add section contain, so if I add
an new method does it go here or to Changed. What is considered a feature, how 
to determine what should I put in the change log etc.

Adding a good git tag guide would also help ( like the one [here](http://git-scm.com/book/en/v2/Git-Basics-Tagging) ) and using 
`git push origin [tagname]` rather than creating tags via the Github, as well as using 
`git tag -a` etc.

A bonus would be explaining the workflow you have with the change log, though I
guess this guide might not be for beginners. For example, do you actually edit
the change log on every commit you deem worthy for mentioning or a the time of
the release you just review the commits you have done and pick the most
important?

And for the extremely ocd/nitpicking question of the day:
Within a change log section (example Added) do you keep the additions
chronological (first-to-last) or in reverse (like the commit history, git log)?

Thanks again for the guide and your effort put into it.

**Comment by JDGrimes** [comment]
> What does Add section contain, so if I add an new method does it go here or to Changed.

I have the same question.

**Comment by mockturtl** [comment]
> For example, does a removed method go into the Removed section or Changed section?

Breaking changes should be called out as such.

###### proposal

All sections are optional.  They **SHOULD** appear in the following order, from most to least important:

- security
- breaking
- deprecated
- additions
- bugfixes

List items in a section **MAY** link to relevant issues or commits.

###### motivation

_This section is non-normative._

Changelogs are for engineers.  Automatic generation of manager- or customer-facing release notes  from a changelog (say, mapping "additions" to "new features") may be possible, but is not a primary design goal.

**Comment by olivierlacan** [comment]
I think the ordering or section is entirely up to the maintainer's discretion. Different releases may require different ordering. Especially if you submit to the idea that empty sections are valuable information about the lack of a specific type of change.
