### ISSUE TITLE
The CHANGELOG.md has an extra trailing whitespace

### ISSUE THREAD

**Issue by IsawU** [olivierlacan/keep-a-changelog#440]
This will potentially leave many projects with this error, if a changelog is first created by copying from the website.

```
…snip…
## [Unreleased]

### Added <--------------- HERE

- Added Dutch translation

…snip…
```

**Comment by olivierlacan** [comment]
Fixed via 46c63ecacadfd94c79f5a60fb2028ff8991b5ed5
