### ISSUE TITLE
v1.1.0 is not in CHANGELOG.md 

### ISSUE THREAD

**Issue by dbrakman** [olivierlacan/keep-a-changelog#442]
I'm trying to quickly find what changed between 1.0.0 and 1.1.0 but can't find a `## [1.1.0]` section in `CHANGELOG.md`, and the `## [Unreleased]` section is empty.

**Comment by olivierlacan** [comment]
It's been there since 2019: https://github.com/olivierlacan/keep-a-changelog/commit/db8179a10fdce6b9a1c0a807df971f8ba2eea2da

**Comment by dbrakman** [comment]
Sorry, I had been looking at the [version](https://github.com/olivierlacan/keep-a-changelog/blob/v1.1.0/CHANGELOG.md) as of the v1.1.0 tag but should have checked `main`
