### ISSUE TITLE
I recommend this date format

### ISSUE THREAD

**Issue by throwaway-d** [olivierlacan/keep-a-changelog#452]
> Regional date formats vary throughout the world and it's often difficult to find a human-friendly date format that feels intuitive to everyone. The advantage of dates formatted like `2017-07-17` is that they follow the order of largest to smallest units: year, month, and day. This format also doesn't overlap in ambiguous ways with other date formats, unlike some regional formats that switch the position of month and day numbers. These reasons, and the fact this date format is an [ISO standard](http://www.iso.org/iso/home/standards/iso8601.htm), are why it is the recommended date format for changelog entries.

I recommend this date format `Feb 16, 2023` which is very understandable for everyone.
Example of a project using the above format: https://codeberg.org/nesaku/BiblioReads/src/branch/main/CHANGELOG.md

**Comment by axd1967** [comment]
> I recommend this date format `Feb 16, 2023` which is very understandable for everyone. Example of a project using the above format: https://codeberg.org/nesaku/BiblioReads/src/branch/main/CHANGELOG.md

Definitely not. 

Your argument is exactly contrary to the argument that is being laid on the table: the format should be unambiguous, an international standard exists that deals precisely with this problem, and it makes sorting more difficult. Additionally, it requires the user to understand the language used (in your example, "Feb").

**Comment by olivierlacan** [comment]
This has been debated ad nauseam. The recommendation for ISO dates still stands: YYYY-MM-DD.
