### ISSUE TITLE
Types of changes - Add missing types to the example CHANGELOG.md

### ISSUE THREAD

**Issue by shoulders** [olivierlacan/keep-a-changelog#459]
Not all of the `Types of changes` are present in your own `CHANGELOG.md` which is used as an example.

Can you add the missing types into your `CHANGELOG.md`

Types of changes

-  Added for new features.
- Changed for changes in existing functionality.
- Deprecated for soon-to-be removed features.
- Removed for now removed features.
- Fixed for any bug fixes.
- Security in case of vulnerabilities.

**Comment by olivierlacan** [comment]
I can't add all the types of changes since not all of them are relevant to this project's changelog. That's the point of showing them on the site with context instead. Sorry.
