### ISSUE TITLE
Evangelism on GitHub

### ISSUE THREAD

**Issue by Zearin** [olivierlacan/keep-a-changelog#46]
## This is all well and good, but…

I love this project’s goal, but even some of the best ideas didn’t succeed on merit alone.  People who believed in those ideas talked to people they know, and got others on board.  

(That’s how Isaac Schlueter [got npm to become the _de facto_ package manager for Node.js](http://thechangelog.com/101/)! The link is to a podcast episode—ironically, from “The Changelog” podcast.  The part I am citing starts at 8:15, and goes on for the next minute or two.)
## I Propose…

…That everyone who believes in the **Keep A Changelog** mission should start opening Issues or Pull Requests, asking repo owners and contributors to convert to the changelog format described by this project.  
### Recommendations
- **Spread the word.** Always mention the http://keepachangelog.com URL in your Issues or Pull Requests.
- **Make it easy for others to convert.**  I’ve often found change logs that are pretty close to official format, but organized just a little bit differently.  I recommend editing these yourself and sending a Pull Request; that will make it much easier for them to accept.  
- **Quantity matters.** If it’s not so easy for you to do the previous item, try and make up for the difference in volume; open as many as you can, and aim for sheer numbers.  The more people are following these guidelines, the more likely it is that others who are more resistant might just reconsider.

**Comment by Zearin** [comment]
Wow.  No responses yet?  Not even a +1 or a -1?

Is this project dead—or dying?

**Comment by olivierlacan** [comment]
Yes. This project is dead because you didn't receive a response in five days.

Dead.

Buried.

Lost in the sand of time.

**Comment by leoj3n** [comment]
Nice :fire: war.

In my opinion, @Zearin needs to refine his ideas and @olivierlacan should address him like a human being if this is really a community project (your response is in bad taste).

**Comment by olivierlacan** [comment]
I don't believe my response is in bad taste. I won't tolerate entitlement here. 

I've been submitting pull requests and issues to encourage open source repo owners to use better change log for the past six months. 

@Zearin's recommendations are fine. I encourage him to apply them, and I hope others do as well. His attitude, however, I can do without.

Considering that this is still a fairly young project with a number of cases not yet properly addressed, I disagree that quantity (as in flooding open source repositories with offers and help to convert their change logs to this recommended format) matters at this point. Quality does. When we achieve something solid enough (I don't think we're very far) then I'll agree that spreading through issues and pull request will become important.

This issue does not propose any changes relevant to the text files in this repository, so I'm closing it.

**Comment by Zearin** [comment]
> @Zearin's recommendations are fine. I encourage him to apply them, and I hope others do as well. His attitude, however, I can do without.

@olivierlacan: 
I did not mean to demonstrate any attitude.  Upon rereading my post (the one that irritated you), I regret some of the words I wrote.  From where I sit now, it *does* seem a tad flippant.  I apologize for my poor choice of words.

However, this is still a conversation I want to have.  Would you consider reopening it?  

----

On a side note, I’m working on some tools for working with CHANGELOG.md files.  They’re not up on GitHub just yet, but they will be soon.  It’s my hope that they will help with evangelism, by offering people who are resistant to converting something that will make it easier.

**Comment by olivierlacan** [comment]
@Zearin I appreciate the apology. Thank you. Make sure you rename your Issue to something more specific to the tool(s) your building.

**Comment by lunemec** [comment]
Yes, the tool ... https://github.com/olivierlacan/keep-a-changelog/issues/51

**Comment by Zearin** [comment]
Sorry for the delay!  

@lunemec Thanks for #51!  I’ll take a look and see if I can incorporate any of those ideas.

In the meantime, my “tool” is something much more simple: a script that translates a CHANGELOG.md into an HTML5 document.  However, my goal is not simply to produce *any* HTML5 document, but a high-quality document—one that respects semantic markup, but which also makes it easy to style with CSS without the headaches of a predefined stylesheet.  

I do this by putting sensible `class` attributes into the markup, but leaving the styling to author (so they can presumably “brand” their changelog to fit their tastes—or their existing website, if they have one).  

I had no plans to limit myself to this one tool, however.  I am interested in making a “toolbox” of things that will make people *want* to follow the guidelines of keep-a-changelog, because the tools will make it easy for them to create changelogs that are so human-friendly that their users will love it.

So, that’s where I am right now.  What do you think?

**Comment by Ajedi32** [comment]
This is something I've been doing for a long time now, ever since I discovered this project. It's a good resource to cite to project owners when explaining the benefits of a CHANGELOG, and its formatting recommendations are sensible and helpful.

I don't necessarily think there needs to be any sort of special, concerted effort here. Advocating for development practices I find useful and effective is just a normal part of my contributions to any open source project I involve myself with. #114 seems like a good step, but not sure there's much required beyond that.

**Comment by olivierlacan** [comment]
I think the project success speaks for itself, if anyone has further ideas, please feel free to reopen.
