### ISSUE TITLE
Change log does not mention whether the project follows Semantic Versioning

### ISSUE THREAD

**Issue by ravage84** [olivierlacan/keep-a-changelog#47]
The guide states:

> What makes a good change log?
> Explicitly mention whether the project follows Semantic Versioning.

https://github.com/olivierlacan/keep-a-changelog/blob/v0.0.6/README.md#what-makes-a-good-change-log

But the change log does not mention whether the project follows Semantic Versioning:
https://github.com/olivierlacan/keep-a-changelog/blob/v0.0.6/CHANGELOG.md

I think the change log should "lead by example" and should implement all its recommended best practices.

**Comment by olivierlacan** [comment]
@ravage84 Good point. Mind sending a Pull Request? ;-)

**Comment by elyscape** [comment]
@olivierlacan Well, does this project follow Semantic Versioning?

**Comment by olivierlacan** [comment]
Closed via #48

**Comment by elyscape** [comment]
I guess that answers my question.
