### ISSUE TITLE
Broken link to ISO 8601 date standard

### ISSUE THREAD

**Issue by shdq** [olivierlacan/keep-a-changelog#547]
**Desctiption**

In [this section](https://keepachangelog.com/en/1.1.0/#bad-practices) link to ISO 8601 date standard is broken.

This problem is across all the translations.

**Potential fix**

Remove the extra close parenthesis.

**Comment by olivierlacan** [comment]
This has already been fixed via 22e81f974c58b817778bcef76fe672c349b73afc

Thanks.

**Comment by phieri** [comment]
The link on the live site is still wrong though.
