### ISSUE TITLE
Keep a Changelog link in example changelog is out of date

### ISSUE THREAD

**Issue by zrev2220** [olivierlacan/keep-a-changelog#567]
The latest version of Keep a Changelog is **v1.1.0**, but the link in the example changelog points to **v1.0.0**.

![image](https://github.com/olivierlacan/keep-a-changelog/assets/22283396/8a235d2c-9ae8-4850-8a37-5ba90cba24bc)

I see this when viewing this link: https://keepachangelog.com/en/1.1.0/.

I skimmed the code briefly, and I'm not sure why this is happening. The link in the [`CHANGELOG.md` file](https://github.com/olivierlacan/keep-a-changelog/blob/b30e4e13acfcd5bc919e963ddd306cd4d9860ce9/CHANGELOG.md) (at least as of b30e4e13acfcd5bc919e963ddd306cd4d9860ce9) is _correct_, and the site code looks like it just reads that file for the example changelog, so theoretically what I see in `CHANGELOG.md` should be what I see in the example changelog on the site. 🤔

**Comment by edmorley** [comment]
It looks like the pages build hasn't run since March:
https://github.com/olivierlacan/keep-a-changelog/actions/workflows/pages/pages-build-deployment

...and the fix for the version link landed after the last build, in April:
https://github.com/olivierlacan/keep-a-changelog/pull/555

**Comment by edmorley** [comment]
> It looks like the pages build hasn't run since March:
> https://github.com/olivierlacan/keep-a-changelog/actions/workflows/pages/pages-build-deployment

@olivierlacan Hi! Sorry for the at-mention, but just wanted to check you were aware the builds are broken?

**Comment by olivierlacan** [comment]
@edmorley It's been fixed, thanks for the heads up!

**Comment by olivierlacan** [comment]
This issue has been fixed. Thanks for reporting it!
