### ISSUE TITLE
Link to ISO date standard is broken; has a trailing ")"

### ISSUE THREAD

**Issue by Patrickode** [olivierlacan/keep-a-changelog#574]
For reasons I don't understand, the link to the ISO date standard in the [Confusing Dates section](https://github.com/olivierlacan/keep-a-changelog/blob/823f4ce1e02ad4b40625c31f46895e28b03d967e/source/en/1.1.0/index.html.haml#L155) has a trailing `)` in it; `https://www.iso.org/iso-8601-date-and-time-format.html)` instead of `https://www.iso.org/iso-8601-date-and-time-format.html`.

This parenthesis is not in data/links.json. So the parenthesis is showing up somewhere in the substitution process.

**Comment by fgnievinski** [comment]
the code reads:
`date format is an #{link_to "ISO standard", data.links.isodate},`

**Comment by ziemek99** [comment]
It's already been fixed in #541, but the changes aren't updated on the live website for whatever reason.

**Comment by olivierlacan** [comment]
They should be now. We had a build pipeline issue.
