### ISSUE TITLE
Version 1.1.1 not visible at website keepachangelog.com

### ISSUE THREAD

**Issue by gruenich** [olivierlacan/keep-a-changelog#578]
You released keep-a-changelog 1.1.1, but your website keepachangelog.com only shows version 1.1.0. Also calling https://keepachangelog.com/en/1.1.1 returns an http error 404 "not found".

This problem might be related to #567

**Comment by olivierlacan** [comment]
We'll need to be more clear that 1.1.1 will not result in a new URL, it's simply patching what's published at the 1.1.0 URL right now. That's what I get for putting the patch "bit" in the URL. :-)

**Comment by gruenich** [comment]
Thank you for your reply! You are right, limiting future URLs to include only the first to numbers of the version (major.minor without .patch) would be helpful.
