### ISSUE TITLE
Update "Can change logs be automatically parsed?"

### ISSUE THREAD

**Issue by skywinder** [olivierlacan/keep-a-changelog#58]
Hi!
I created [Github-Changelog-Generator](https://github.com/skywinder/Github-Changelog-Generator).

It seems, that it exactly, what should be mentioned in Paragraph [Can change logs be automatically parsed?](https://github.com/olivierlacan/keep-a-changelog#can-change-logs-be-automatically-parsed).

My project generate changelog file very close to your changelog conventions.

_bdw: found your article, when try to google standart date format for changelog files - many thanks for explanation! I will implement it in my project in next release_

**Comment by Ajedi32** [comment]
That's a changelog generator, not a changelog parser. Also, it suffers from many of the same problems listed in the "Why can’t people just use a git log diff?" section.

**Comment by skywinder** [comment]
@Ajedi32 Agree with you 👍

**Comment by svetlyak40wt** [comment]
Anyway, guys, if you really need a changelog parser, than try AllMyChanges.com. I wrote this service some time ago and it is really good in parsing and normalization of the changelogs from different formats.

If you have any ideas, why somebody need a standalone changelog parsing utility, please, share your thoughts with me.

**Comment by skywinder** [comment]
@svetlyak40wt 

> If you have any ideas, why somebody need a standalone changelog parsing utility, please, share your thoughts with me.

 because command line tool it faster and could be run automatically with every new release by git hook or whatever.

**Comment by svetlyak40wt** [comment]
> because command line tool it faster and could be run automatically with every new release by git hook or whatever.

Could you please describe a case when somebody wants to run automatic parsing of the changelog by git hook?

**Comment by zapashcanon** [comment]
- a package maintainer from a distribution to avoid breaking things or whatever
- a site web displaying something like "What's new in version x ?"

**Comment by svetlyak40wt** [comment]
In first case, more probably distribution maintainer will not own a git repository to setup any webhooks,  and to keep eye on different changelogs will be more convenient to use parser as a service.

In second case you don't need to parse a changelog, you already have it with some markup – markdown or reStructured. Just render and embed it into the site.

**Comment by nedtwigg** [comment]
There are lots of great reasons to parse a changelog! I just released [spotless-changelog](https://github.com/diffplug/spotless-changelog), which is a keepachangelog  round-trip-parser for the JVM ([javadoc](https://javadoc.jitpack.io/com/github/diffplug/spotless-changelog/spotless-changelog-agg/release~1.1.0/javadoc/com/diffplug/spotless/changelog/Changelog.html)), along with a gradle plugin.  It uses the parsed changelog to calculate the next version number, and then it also updates the changelog for you when you do a publish.

Other use cases would be to check that the breaking changes that get detected by tooling (e.g. [japicc](https://github.com/lvc/japi-compliance-checker)) are noted in the changelog.  One way that I'm using it right now is to help manage a multi-module project where the modules are published at slightly different cadences.  I can use the parsed changelog to help [make sure that a library is never published which accidentally depends on unreleased changes in another library](https://github.com/diffplug/spotless/blob/a62ab5924f35cefb382d835192ef292c6931579b/gradle/changelog.gradle#L36-L42).

(if you'd like to signal boost this effort, here is the [release tweet](https://twitter.com/NedTwigg/status/1217027144737386497?s=20))

**Comment by olivierlacan** [comment]
This project is not here to make or recommended automated tools to create changelogs. That's why we're in this mess in the first place: people not curating human-focused changelogs.

You're free to explore solutions to assist maintainers in the creation of changelogs that follow the guidelines from this project, but there will always be a need for editorial review in order to create useful release notes and changelogs. 

Be careful trying to make things too efficient.

**Comment by nedtwigg** [comment]
> This project is not here to make or recommended automated tools to create changelogs.

Parsing is the opposite of creating/generating! Human-focused changelogs should absolutely be hand-written, but there's no reason they need to be hand-copied into release tags, hand-copied into app store releases, or hand-copied into an auto-update mechanism. Helping users find changelog parsers (not generators) amplifies the value of having a good handwritten `CHANGELOG.md`.
