### ISSUE TITLE
Separate changelogs for different branches

### ISSUE THREAD

**Issue by pravj** [olivierlacan/keep-a-changelog#62]
Hi @olivierlacan,

This is a nice movement you're doing here. :+1: 

My question is that, is it a right convention to use different changelogs for different repository branches?
I think that it's not wrong to have separate changelogs because each branches serves different purpose.

Can you please share your thought on this particular situation?

**Comment by elyscape** [comment]
> each branches serves different purpose.

Could you elaborate on this?  I'm not familiar with this use case.

**Comment by pravj** [comment]
Actually I read it on [vandamme's README](https://github.com/tech-angels/vandamme/#filename) that, `You MAY have different changelog in each branch.`

**Comment by elyscape** [comment]
Huh.
