### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by aishek** [olivierlacan/keep-a-changelog#66]
Olivier, thanks for a great manual! I'd like to translate it into Russian, what do you think?

**Comment by olivierlacan** [comment]
Go for it!

**Comment by hellboy81** [comment]
и как успехи в переводе?

**Comment by aishek** [comment]
@hellboy81 пока как-то деревянно получилось https://github.com/aishek/keep-a-changelog/blob/ru/index-ru.html, а довести воли не хватает

**Comment by olivierlacan** [comment]
@aishek Can you open a pull request to add the Russian translation?

**Comment by aishek** [comment]
@olivierlacan #78 complete. Sorry for long time it tooks. Most important thing I've learned – "Done is better than absolute quality". :ru: :beer: :+1: :checkered_flag: 

So I see translations branch, should I convert my translation into its format?

**Comment by olivierlacan** [comment]
@aishek Wait a bit. @nbibler came to me with a very nice change set I'd like him to merge in separately.

**Comment by nbibler** [comment]
Thank you @aishek! I took your source and converted it back to Markdown format. Added it as the first locale available.

http://keepachangelog.com/ru/

**Comment by aishek** [comment]
@nbibler @olivierlacan well done! :+1:
