### ISSUE TITLE
Why the emphasis on open source?

### ISSUE THREAD

**Issue by tallesl** [olivierlacan/keep-a-changelog#68]
The website text tightly relates the proposed change log format with open source projects:

> *of notable changes for each version of an* ***open source project***
> (...)
> *If you don’t care, why are you contributing to* ***open source****?*
> (...)
> *about why* ***open source maintainers and contributors*** *should care*
> (...)
> *what I hope will become a better CHANGELOG file convention for all* ***open source projects****. Can the* ***open source community*** *learn from its mistake*

I came to know keepachangelog.com by searching for a standard to apply in the (private) company I work at, and so far it seems a pretty good format to use. I assure you that this problem (bad change logs or the complete lack of it) affects many projects out there, both closed and open source.

Don't you guys think that adherence to the format by the *closed source world* would benefit the industry as a whole?

I actually don't *mind* (not at all) the open source references along the *manifesto* (can I call it a manifesto?), I'm just passing by giving food for thought.

**Comment by potherca** [comment]
For a lot of closed source projects I have worked on, the changelog was either not a plain text file and/or not kept with the codebase as it was deemed important enough for users/customers to read as well.

It also, often, had business value (like version numbers), so developers did not really get to decide what went into the changelog, other than really technical stuff.

This, other factors, and the fact that open-source/proprietary goals are contradictory (improving things for everyone vs. improving things for one party at a cost to others) would make it a lot less valuable and a lot less practical to try and **convince** closed source projects to adhere to an (open-sourced) standard.

Of course, like what happened with [semver](http://semver.org/), there is no reason _not_ to adapt this standard as a closed source product/project. Incidentally semver does not make any mention in regards to open/closed source :smile_cat:

**Comment by olivierlacan** [comment]
Good point.

**Comment by olivierlacan** [comment]
Fixed with 5daa2fda5733538b70abe394798e8612e38c5de3
