### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by tallesl** [olivierlacan/keep-a-changelog#69]
Hi,

I'm just passing by ([again](68)) to tell you that I've translated the content to [Brazilian Portuguese :pineapple:](http://tallesl.github.io/keep-a-changelog/)

**Comment by olivierlacan** [comment]
Awesome!

**Comment by olivierlacan** [comment]
Want to keep it on your own domain or make a PT BR link on keepachangelog.com?

**Comment by tallesl** [comment]
Either way I'm fine!

P.S.: I've added [a note at the end of my version](https://github.com/tallesl/keep-a-changelog#isto-%C3%A9-uma-tradu%C3%A7%C3%A3o) stating that is a translation. It reads (in english):

### This is a translation

*[Translator](https://github.com/tallesl) speaking*.

This is a translation of [keepachangelog.com](http://keepachangelog.com).

To contribute with the discussion and the elaboration of the document, use the [original repository](https://github.com/olivierlacan/keep-a-changelog). To contribute with the translation, use [this fork](https://github.com/tallesl/keep-a-changelog).

**Comment by variadico** [comment]
Maybe there should be a localization folder, no? That way there can be a standard way of translating and finding Keep a Changelog in different languages.

Just my two cents. :)

**Comment by olivierlacan** [comment]
@variadico Good point. @tallesl I'll prepare a translations directory.

**Comment by nbibler** [comment]
Thank you, @tallesl! I converted your translation into Markdown in the new Middleman app. I hope I didn't break anything in the process. I believe I caught all of the `em`'s. ;) Let us know if there's anything wrong or missing.

http://keepachangelog.com/pt-BR/
