### ISSUE TITLE
Changelog for each minor release

### ISSUE THREAD

**Issue by adamquaile** [olivierlacan/keep-a-changelog#7]
With large teams and lots of changes, these file can be pretty big, and one changelog would be massive. 

On large projects, I personally tend to create a changelog for each minor version, like `CHANGELOG-2.4.md`, `CHANGELOG-2.5.md`. 

I then split each changelog into sections, like "changes introduced in x.y.3", "changes in x.y.1". 

I think large projects like symfony also do similarl; see https://github.com/symfony/symfony/blob/master/CHANGELOG-2.2.md

**Comment by lunemec** [comment]
:+1:  for single file. I doubt it would get **really** big anytime soon (meaning in order of GB).

**Comment by olivierlacan** [comment]
My answer is one single file, don't make people hunt for important information. Text is cheap, Git is made for text.
