### ISSUE TITLE
Add database versions

### ISSUE THREAD

**Issue by wchad** [olivierlacan/keep-a-changelog#70]
Hi,

How do I add information database versions in the changelog ?

**Comment by olivierlacan** [comment]
Can you give a little more context about this? Not sure what you're referring to.

**Comment by wchad** [comment]
Let's say I made a change in the database, and need to register in the changelog, How do record this update?

**Comment by tallesl** [comment]
You should definitely version your database (along the code), but I'm not sure about stating it in the changelog.

If the database change is originated from a bug fix, you log the bug fix.
If it's a new feature, you log the new feature.
If it's a depreciation, well, you get the picture.

If you have such need (to relate the database changes), the way you version your database should tell you that (your SQL scripts, rake migrations, whatever).

(IMO)

**Comment by mbrand12** [comment]
From what I gather, the point of changelog is to make changes that are important to your users (that ones that actually change the user experience) more clear. Changing a public method or adding a new class with public methods is one. 

On the other hand making a new table in the database should not be that important to the user if the user doesn't need to manipulate the database tables directly. In some way it would be like recording private methods in the changelog, the user doesn't use them directly so the user should not care about it. At least that is how is see it.

**Comment by wchad** [comment]
Perfect, thank you all for your help

**Comment by PikachuEXE** [comment]
Close?

**Comment by olivierlacan** [comment]
@PikachuEXE You got it.
