### ISSUE TITLE
Parseable variations (Markdown, RST, Wiki, text/plain)

### ISSUE THREAD

**Issue by prof-milki** [olivierlacan/keep-a-changelog#8]
Agreeing on a common format is difficult.

For freshcode.club (a freshmeat replacement), I've decided to allow a few variations, but still enforce a common scheme (which k-a-c captures pretty well).
Here primarily to keep it parsable without too many false positives:  
[http://fossil.include-once.org/freshcode/wiki/AutoupdateChangelog](http://fossil.include-once.org/freshcode/wiki/AutoupdateChangelog)

I'd have presumed Markdown was more common, but in particular Python projects (well, if they have a changelog anyway) seem to lean towards ReStructuredText rather ([PEP287](http://legacy.python.org/dev/peps/pep-0287/) and hence PyPI support).

Plain text structures are not that far off from MarkDown either, and I'd need to support it since CPAN::Canages::Spec is the only widespread format.

What I personally find more relevant to differentiate release note changelogs from commit logs is leaving out e.g. attributions `(written by <author@example.com)` or ticket numbers `(Closes #257)` which are largely irrelevant to actual feature changes. Maybe the summarization intent of changelogs could be more stressed?

**Comment by olivierlacan** [comment]
Closing. The format is Markdown.
