### ISSUE TITLE
Broken link to CHANGELOG.md on website.

### ISSUE THREAD

**Issue by drumrock** [olivierlacan/keep-a-changelog#80]
On http://keepachangelog.com/ phrase "contains what I hope will become a better CHANGELOG file convention." links to 404 Page Not Found.

**Comment by drumrock** [comment]
And other links to CHANGELOG.md are broken there too.

**Comment by nbibler** [comment]
Confirmed :+1:. I broke the links when I transitioned to using the Middleman build. Thanks for the heads up.

**Comment by strugee** [comment]
@nbibler FWIW, the W3C maintains a tool that can crawl your website looking for broken links. I ran it on keepachangelog.com; [here are the results][1]. tl;dr: `apple-touch-icon.png`, `favicon.png`, `CHANGELOG.md`, `CONTRIBUTING.md`, `LICENSE` and `README.md` are all broken.

 [1]: https://validator.w3.org/checklink?uri=http%3A%2F%2Fkeepachangelog.com%2F&hide_type=all&recursive=on&depth=2&check=Check

**Comment by nbibler** [comment]
This should be addressed with fbe5b2ef08f7c88a523ab8f62ae9af4bfec6aeaa. I'll run the link checker after the cache updates.

**Comment by nbibler** [comment]
Seems good! Thanks for letting us know! :)
