### ISSUE TITLE
How to make version as links

### ISSUE THREAD

**Issue by aik099** [olivierlacan/keep-a-changelog#81]
On the https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md you have versions are links to tag compare. I've created my change log at https://github.com/qa-tools/qa-tools/blob/develop/CHANGELOG.md and this doesn't happen. Also the user mentions doesn't work.

Any idea why?

**Comment by Art4** [comment]
You must add the links in the bottom of the file. See the raw changlog file: https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/master/CHANGELOG.md

```
[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.2.0...HEAD
[0.2.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.1.0...v0.2.0
[0.1.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.8...v0.1.0
[0.0.8]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.7...v0.0.8
...
```

**Comment by aik099** [comment]
Thanks.
