### ISSUE TITLE
Suggestion for Issue Tracking

### ISSUE THREAD

**Issue by Mortiferr** [olivierlacan/keep-a-changelog#94]
I suggest you organize your tags something like this. They are colour-coded by category.
![screencapture-github-com-mortiferr-future-posts-labels-1453821604884](https://cloud.githubusercontent.com/assets/13282318/12584695/5fd64bec-c40e-11e5-99d5-0b53918d23cf.png)

**Comment by olivierlacan** [comment]
Most if not all our issues are discussions. These tags are great but not appropriate for this project. Thank you.
