### ISSUE TITLE
Prefix convention

### ISSUE THREAD

**Issue by danielgomezrico** [olivierlacan/keep-a-changelog#98]
Im using some convention on my commits same for changelog:

Types:
- `=`: UPDATE
- `+`: ADD
- `-`: REMOVE
- `F`: FIX
- `C`: CLEAN

Example:

```
# v 1.0.0 ....
= change the dialogs style`: means there was an update over the dialogs style.
+ new dialogs library`: means you added dialogs library.
F showing dialogs crash`: means that you fixed showing dialogs crash.
F when user try to login crash`: means that you fixed this bug
```

so when you see the list you see what is for cleaning, whats removed, whats added, etc...
If you want to see how the commit history looks check https://github.com/MakinGiants/todayhistory/commits/develop

What do you think?

**Comment by cdeszaq** [comment]
In general, I, personally, am not a fan of most abbreviations or symbols to denote things. It can work for situations where everyone is on the same page and onboarding is infrequent, but for wider audiences, I've not found abbreviations to be well regarded.

That said, I think such a convention in _commit messages_ makes a lot of sense, and commit messages should in general contain the information you're capturing. I must admit, however, I'm not sure how closely commit messages align to changelogs.

**Comment by danielgomezrico** [comment]
For changelogs may help to show faster what was a fix, an update, a cleanup... yeah, conventions are not great but when there are a lot, those are just 5. Another way may be having the labels withs caps on, like:

```
# v 1.0.0 ....
- UPDATE change the dialogs style`: means there was an update over the dialogs style.
- ADD new dialogs library`: means you added dialogs library.
- FIX showing dialogs crash`: means that you fixed showing dialogs crash.
- FIX when user try to login crash`: means that you fixed this bug
```

**Comment by cryode** [comment]
> It’s made for humans, not machines, so legibility is crucial.

I believe the groups and more human-readable format of the current standard is best. The format does not require additional training or a key to understand symbols, and is easily understood by non-developers (such as projects managers, product owners, QA team, etc.), allowing the document to be used as a reference by all parties.

**Comment by olivierlacan** [comment]
Yep, sorry, I don't think this is a good idea. As we've established repeatedly, this is for humans. The machine-parseable aspect is not a priority. And honestly, if writing a category header is the efficiency bottleneck, I think you may be over-optimizing.
